---
title: "Data Upload Automation: Emotion_Labeling"
author: "Kyle Murray"
date: "6/3/2020"
output: html_document
---
#Setup 
Loading library, set knitr and scientific notation
```{r Setup}
#Loading library
library(dplyr)
library(tidyverse)
library(data.table)
library(kableExtra)


```
##Import 
Import Measurement, Pedigree data and NDA structure

```{r Import}
#Clear Environment Setup
rm(list = ls())

Emotion_Labeling_REDCAP <- read.csv("Redcap_Data.csv")
Pedigree <- read.csv("Reference_Pedigree.csv")
Emotion_Labeling_NDA <- read.csv("elt01_template.csv", skip=1)


```
##Rename Columns 
Replace column names with NDA specified names 

```{r Rename Columns}
#rename elt_exp names
eltpart1_exp <- "oc_elt_exp"
num_items <- seq(1:8)
new_eltpart1_names <- paste(eltpart1_exp, num_items, sep = "_")

#rename elt_rec names
eltpart2_rec <- "oc_elt_rec"
num_items <- seq (1:4) 
new_eltpart2_names <- paste(eltpart2_rec, num_items, sep = "_")

#replace old eltpart1 names with new names
eltpart1_exp <- "eltpart1_exp"
num_items <- seq (1:8)
old_eltpart1_names <- paste(eltpart1_exp, num_items, sep = "")
setnames(Emotion_Labeling_REDCAP, old_eltpart1_names, new_eltpart1_names)

#replace old eltpart2 names with new names
eltpart2_rec <- "eltpart2_rec"
num_items <- seq (1:4)
old_eltpart2_names <- paste(eltpart2_rec, num_items, sep = "")

setnames(Emotion_Labeling_REDCAP, old_eltpart2_names, new_eltpart2_names)
```

``` {r Prep Sheet}
#Assign timepoint from redcap_event_name
Emotion_Labeling_REDCAP$timepoint = sapply(strsplit(as.character(Emotion_Labeling_REDCAP$redcap_event_name), split = '_', fixed = T), function(x) (x[2]))

Emotion_Labeling_REDCAP <- select(Emotion_Labeling_REDCAP, c(Fam_ID = fam_id,  timepoint, starts_with("oc_elt_")))
Emotion_Labeling_REDCAP <- select(Emotion_Labeling_REDCAP, -c(oc_elt_notes))

#Select relevant pedigree information 
Pedigree_T1 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time1Date, interview_age = MomAge_T1, child_sex = ChildGender, GroupAssignment), timepoint = 1 )
Pedigree_T2 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time2Date, interview_age = MomAge_T2, child_sex = ChildGender, GroupAssignment), timepoint = 2 )
Pedigree_T3 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time3Date, interview_age = MomAge_T3, child_sex = ChildGender, GroupAssignment), timepoint = 3 )
Pedigree_T4 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time4Date, interview_age = MomAge_T4, child_sex = ChildGender, GroupAssignment), timepoint = 4 )

#Merge pedigree info
Pedigree_Prep <- rbind(Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4)

#merge Pedigree info and Redcap data
EL_PREP <- merge(Pedigree_Prep, Emotion_Labeling_REDCAP,by = c("timepoint","Fam_ID"), all = TRUE)

#clean environment
# rm(Pedigree, Pedigree_Prep, Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4, Emotion_Labeling_REDCAP)
```

```{r Calculated Columns}
#add calculated colums to dataframe
exp <- colnames(select(EL_PREP, c("oc_elt_exp_2", "oc_elt_exp_4", "oc_elt_exp_6", "oc_elt_exp_8")))

rec <- colnames(select(EL_PREP, c("oc_elt_rec_1", "oc_elt_rec_2", "oc_elt_rec_3", "oc_elt_rec_4")))
#add mean coulumns 
EL_PREP$oc_elt_exp_total <- rowMeans(EL_PREP[,exp], na.rm = TRUE)
EL_PREP$oc_elt_rec_total <- rowMeans(EL_PREP[,rec], na.rm = TRUE)

#add NA check column
EL_PREP$NACheck <- rowSums(is.na(select(EL_PREP, starts_with("oc_elt_"))))/ncol(dplyr::select(EL_PREP, starts_with("oc_elt_")))

#EL_PREP$EL_total_cor <- ifelse(EL_PREP$NACheck < 0.67, rowMeans(EL_PREP[,oc_elt_total], na.rm = TRUE), "NA")

#Separate Data into NA% response 
EL_DROP <- EL_PREP[EL_PREP$NACheck > 0.67, ]
EL_PREP67 <- EL_PREP[EL_PREP$NACheck <= 0.67, ]
EL_PREP100 <- EL_PREP[EL_PREP$NACheck <= 0, ]
```

```{r NDA Sheet}
#Move relevant info to NDA dataframe
Emotion_Labeling_NDA <- select(EL_PREP67, c(subjectkey = child_guid, src_subject_id = child_famID, interview_date, interview_age, sex = child_sex, visit = timepoint, starts_with("oc_elt_")))

# Recreate first line in orignial NDA file
Emotion_Labeling_NDA <- bind_rows(Emotion_Labeling_NDA, EL_PREP67)
first_line <- matrix("", nrow = 1, ncol = ncol(Emotion_Labeling_NDA))
first_line[,1] <- "el"
# assign the second cell in first_line as "el"
first_line[,2] <- "1"

# NDA output ---------
# Create a new file in folder called el.csv, and put first line into this file
# el.csv file will be saved into same folder as current r script
write.table(first_line, file = "el01.csv", sep = ",", append = FALSE, quote = FALSE, na = "", col.names = FALSE, row.names = FALSE)

# Append data in Emotion_Ladeling_NDA into el.csv file 
write.table(Emotion_Labeling_NDA, file = 'el01.csv', sep = ",", append = TRUE, na = "", quote = FALSE, row.names = FALSE)
```

```{r Table 67}
#Establish 67% Table dataframe and import relevant data
Progress67 <- select(EL_PREP67, c(Fam_ID, GroupAssignment, timepoint, starts_with("oc_elt_")))

EL_PREP67[, c(10,12,14,16:23)] <- sapply(EL_PREP67[, c(10,12,14,16:23)] ,as.numeric)

# Calculate row mean for each individual  
#Progress67$Row_Mean <- rowMeans(select(EL_PREP67,c(starts_with("oc_elt"))), na.rm = T)

Progress67$Row_Mean <- rowMeans(select(EL_PREP67, c(10,12,14,16:23)))

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress67$Fam_ID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress67$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Group by GroupAssissignment and Timepoint, and calculate the Group Mean
Progress_Mean <- Progress67 %>%
  group_by(GroupAssignment,timepoint,site) %>%
  summarise(GroupMean = mean(Row_Mean,na.rm = T),count = n())

# Select only UO Mean
UO <- Progress_Mean[Progress_Mean$site == "UO",]
# Select only UPMC Mean 
UPMC <- Progress_Mean[Progress_Mean$site == "UPMC",]

# Calculate Both site Mean 
Both_site_Mean <- Progress67 %>%
  group_by(GroupAssignment, timepoint) %>%
  summarise(BothSite_EmotionalLabeling_Mean = mean(Row_Mean,na.rm = T),n = n())

# Change GroupMean Column names according to site
colnames(UO)[colnames(UO) == "GroupMean"] = "UO_EmotionalLabeling"
colnames(UPMC)[colnames(UPMC) == "GroupMean"] = "UPMC_EmotionalLabeling"

# Combine UO,UPMC and both_site data 
Mean_Table67 <- data.frame(UO[,c("UO_EmotionalLabeling")],UPMC[,"UPMC_EmotionalLabeling"],Both_site_Mean[,c("BothSite_EmotionalLabeling_Mean","n","GroupAssignment")])

# Convert Mean_Table, make original column as row
Mean_Table67 <- t(Mean_Table67)

# Make Mean_Table as a data.frame
Mean_Table67 <- data.frame(Mean_Table67)

# Reorder Mean_Table
Mean_Table67 <- Mean_Table67[c(5,6,7,8,9,10,11,12,1,2,3,4)]

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table67, names(Mean_Table67), Timepoint_names)

# Table output ----------
# Add a header 
kable(Mean_Table) %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 1, "Controls Group means" = 4, "FSU Group means" = 4, "DBT Group means" = 4)) %>%
  add_header_above(c("Emotion Labeling Mean Table 67%" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")
```




```{r Table 100}
Progress100 <- select(EL_PREP100, c(Fam_ID, GroupAssignment, timepoint, starts_with("oc_elt_")))

EL_PREP100[, c(10,12,14,16:23)] <- sapply(EL_PREP100[, c(10,12,14,16:23)],as.numeric)

# Calculate row mean for each individual  
Progress100$Row_Mean <- rowMeans(select(EL_PREP100, c(10,12,14,16:23)))

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress100$Fam_ID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress100$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Group by GroupAssissignment and Timepoint, and calculate the Group Mean
Progress_Mean <- Progress100 %>%
  group_by(GroupAssignment,timepoint,site) %>%
  summarise(GroupMean = mean(Row_Mean,na.rm = T),count = n())

# Select only UO Mean
UO <- Progress_Mean[Progress_Mean$site == "UO",]
# Select only UPMC Mean 
UPMC <- Progress_Mean[Progress_Mean$site == "UPMC",]

# Calculate Both site Mean 
Both_site_Mean <- Progress100 %>%
  group_by(GroupAssignment, timepoint) %>%
  summarise(BothSite_EmotionalLabeling_Mean = mean(Row_Mean,na.rm = T),n = n())

# Change GroupMean Column names according to site
colnames(UO)[colnames(UO) == "GroupMean"] = "UO_EmotionalLabeling"
colnames(UPMC)[colnames(UPMC) == "GroupMean"] = "UPMC_EmotionalLabeling"

# Combine UO,UPMC and both_site data 
Mean_Table100 <- data.frame(UO[,c("UO_EmotionalLabeling")],UPMC[,"UPMC_EmotionalLabeling"],Both_site_Mean[,c("BothSite_EmotionalLabeling_Mean","n","GroupAssignment")])

# Convert Mean_Table, make original column as row
Mean_Table100 <- t(Mean_Table100)

# Make Mean_Table as a data.frame
Mean_Table100 <- data.frame(Mean_Table100)

# Reorder Mean_Table
Mean_Table100 <- Mean_Table100[c(5,6,7,8,9,10,11,12,1,2,3,4)]

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table100, names(Mean_Table100), Timepoint_names)

# Table output ----------
# Add a header 
kable(Mean_Table) %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 1, "Controls Group means" = 4, "FSU Group means" = 4, "DBT Group means" = 4)) %>%
  add_header_above(c("Emotion Labeling Mean Table 100%" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")


```

```{r N's Table}
#### Original Table ####
# Original by site
N_ori <- Progress_Mean %>%
  group_by(timepoint, site, GroupAssignment) %>% 
  summarise(n_ori = n())

# Original both site 
N_ori_BothSite <-  %>%
  group_by(timepoint, GroupAssignment) %>% 
  summarise(BothSite_Original_N = n())


#### 67% table ####
# 67% by site 
N67 <- Progress67 %>%
  group_by(timepoint, site, GroupAssignment) %>% 
  summarise(n_67 = n())

# 67% both site 
N67_BothSite <- Progress67 %>%
  group_by(timepoint, GroupAssignment) %>% 
  summarise(BothSite_67_N = n())

#### 100% table ####
N100 <- Progress100 %>%
  group_by(timepoint, site, GroupAssignment) %>% 
  summarise(n_100 = n())

# 100% both site 
N100_BothSite <- Progress100 %>%
  group_by(timepoint, GroupAssignment) %>% 
  summarise(BothSite_100_N = n())

#### N table ####

# combine all three n table 
N_bySite <- cbind(N_ori, N67, N100)
# Bind both site data 
BothSite_N <- cbind(N_ori_BothSite, N67_BothSite, N100_BothSite)


# Seperate UO and UPMC data 
UO_N <- data.frame(N_bySite[N_bySite$site == "UO",])
UPMC_N <- data.frame(N_bySite[N_bySite$site == "UPMC",])

# Change column names 
colnames(UO_N)[colnames(UO_N) == "n_ori"] = "UO_EL_Original_N"
colnames(UO_N)[colnames(UO_N) == "n_67"] = "UO_EL_67_N"
colnames(UO_N)[colnames(UO_N) == "n_100"] = "UO_EL_100_N"

colnames(UPMC_N)[colnames(UPMC_N) == "n_ori"] = "UPMC_EL_Original_N"
colnames(UPMC_N)[colnames(UPMC_N) == "n_67"] = "UPMC_EL_67_N"
colnames(UPMC_N)[colnames(UPMC_N) == "n_100"] = "UPMC_EL_100_N"

# Create N table (Selecting columns from UO_N, UPMC_N, BothSite_N)
N <- data.frame(UO_N[, c("timepoint","UO_EL_Original_N", "UO_EL_67_N", "UO_EL_100_N")], 
                UPMC_N[, c("UPMC_EL_Original_N", "UPMC_EL_67_N", "UPMC_EL_100_N", "GroupAssignment")],
                BothSite_N[, c("BothSite_Original_N", "BothSite_67_N", "BothSite_100_N", "GroupAssignment")])

# Reorder N table base on GroupAssignment 
N <- N[order(N$GroupAssignment),]

# Convert data frame to numeric
N <- as.data.frame(sapply(N, as.numeric))

# Transfer N table from Horzontal to Vertical
N <- data.frame(t(N))

# Colculate Total N 
N$T1 <- rowSums(N[,c(1,5,9)])
N$T2 <- rowSums(N[,c(2,6,10)])
N$T3 <- rowSums(N[,c(3,7,11)])
N$T4 <- rowSums(N[,c(4,8,12)])

# Timepoint names 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4", "T1","T2", "T3", "T4")

# Rename column name 
setnames(N, names(N), Timepoint_names)

N <- N[-c(1,8,12),]


# Remove un-needed lines in table
# N <- N[-c(1,2,3),]

# Total number colculation 


kable(N) %>%
  kable_styling(bootstrap_options = c("striped"), fixed_thead = T) %>%
  add_header_above(c(" " = 1, "DBT Group" = 4, "Control Group" = 4, "FSU Group" = 4, "Totals" = 4)) %>%
  add_header_above(c("Participant Numbers" = 17)) %>%
  column_spec(c(1,5,9,13), border_right = T, include_thead = T) %>%
  column_spec(2:17, width_min = "2cm", width_max = "2cm") %>%
  row_spec(7:9, background = "#d3d3d3")

```









