---
title: "CBCL_Table_Mean"
author: "Austin Fisenko"
date: "7/9/2020"
output: html_document
---

```{r setup}
#empty Global Environment
rm(list = ls())
# Import Packages Needed
library(dplyr)
library(tidyverse)
library(eeptools)
library(data.table)
library(knitr)
library(kableExtra)

knitr::opts_chunk$set(echo = TRUE, include = FALSE)
#Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

fsep <- .Platform$file.sep;

# Set the working directory -----
# for Bryan
# setwd("C:/Users/bryan/Documents/GitHub/DataUploadAutomation/Measures/CBCL")
setwd("D:/Austin/College (D-Drive)/DataUploadAutomation/Measures/CBCL")

#sentific notation, round up to 3 digits
options(digits = 3)

```

```{r import}
# Import Pedigree and NDA Structure
Pedigree <- read.csv("Reference_Pedigree.csv")
NDA_CBCL <- read.csv("cbcl1_501_template.csv", skip = 1)

# Import cbcl Files
UO_T1_cbcl <- read.csv(file = 'UO_T1_Qualtrics.csv', stringsAsFactors = FALSE)
UO_T2_cbcl <- read.csv(file = 'UO_T2_Qualtrics.csv', stringsAsFactors = FALSE)
UO_T3_cbcl <- read.csv(file = 'UO_T3_Qualtrics.csv', stringsAsFactors = FALSE)
UO_T4_cbcl <- read.csv(file = 'UO_T4_Qualtrics.csv', stringsAsFactors = FALSE)
UPMC_T1_cbcl <- read.csv(file = 'UPMC_T1_cbcl.csv', stringsAsFactors = FALSE)
UPMC_T2_cbcl <- read.csv(file = 'UPMC_T2_cbcl.csv', stringsAsFactors = FALSE)
UPMC_T3_cbcl <- read.csv(file = 'UPMC_T3_cbcl.csv', stringsAsFactors = FALSE)
UPMC_T4_cbcl <- read.csv(file = 'UPMC_T4_cbcl.csv', stringsAsFactors = FALSE)

```

```{r rename columns}
# Create list of new variable names 
new_cbcl_names <- sprintf("srm_cbcl_%03d", seq(1:100))

# Create list of old variable names so we can replace them with the new ones
# Since the question names change by timepoint we'll have to make unique lists by timepoint. 
old_UO_cbcl_names_T1 <- sprintf("Q264_%01d", seq(1:100))
old_UPMC_cbcl_names_T1_T4 <- sprintf("Q15.1_%01d", seq(1:100))

#Same as above for different timepoints
old_UO_cbcl_names_T2 <- sprintf("Q368_%01d", seq(1:100))
old_UPMC_cbcl_names_T2_T3 <- sprintf("Q12.1_%01d", seq(1:100))

#Same as above but UO has a different question number to select for each timepoint
old_UO_cbcl_names_T3 <- sprintf("Q534_%01d", seq(1:100))

#Same as above for UO timepoint 4
old_UO_cbcl_names_T4 <- sprintf("Q828_%01d", seq(1:100))


# Replace UO column names (there may be errors from the CBCL TEXT question responses) 
setnames(UO_T1_cbcl, old_UO_cbcl_names_T1, new_cbcl_names)
setnames(UO_T2_cbcl, old_UO_cbcl_names_T2, new_cbcl_names)
setnames(UO_T3_cbcl, old_UO_cbcl_names_T3, new_cbcl_names)
setnames(UO_T4_cbcl, old_UO_cbcl_names_T4, new_cbcl_names)

# Replace UPMC column names (there may be errors from the CBCL TEXT question responses)
setnames(UPMC_T1_cbcl, old_UPMC_cbcl_names_T1_T4, new_cbcl_names)
setnames(UPMC_T2_cbcl, old_UPMC_cbcl_names_T2_T3, new_cbcl_names)
setnames(UPMC_T3_cbcl, old_UPMC_cbcl_names_T2_T3, new_cbcl_names)
setnames(UPMC_T4_cbcl, old_UPMC_cbcl_names_T1_T4, new_cbcl_names)

```

```{r prep sheet}
# Edit UO cbcl Time 1 - 4 to have only cbcl quesions and the FamID. 
UO_T1_cbcl <- select(UO_T1_cbcl, c(FamID = Q221, contains("cbcl")))
UO_T2_cbcl <- select(UO_T2_cbcl, c(FamID = Q116, contains("cbcl")))
UO_T3_cbcl <- select(UO_T3_cbcl, c(FamID = Q174, contains("cbcl")))
UO_T4_cbcl <- select(UO_T4_cbcl, c(FamID = Q203, contains("cbcl")))

# Edit UPMC cbcl Time 1 - 4 to have only cbcl quesions and the FamID.
UPMC_T1_cbcl <- select(UPMC_T1_cbcl, c(FamID = Q1.2, contains("cbcl")))
UPMC_T2_cbcl <- select(UPMC_T2_cbcl, c(FamID = Q1.2, contains("cbcl")))
UPMC_T3_cbcl <- select(UPMC_T3_cbcl, c(FamID = Q1.2, contains("cbcl")))
UPMC_T4_cbcl <- select(UPMC_T4_cbcl, c(FamID = Q1.2, contains("cbcl")))

# Bind UO and UPMC cbcl Data By Time Point 
cbcl_T1 <- rbind(UO_T1_cbcl, UPMC_T1_cbcl)
cbcl_T2 <- rbind(UO_T2_cbcl, UPMC_T2_cbcl)
cbcl_T3 <- rbind(UO_T3_cbcl, UPMC_T3_cbcl)
cbcl_T4 <- rbind(UO_T4_cbcl, UPMC_T4_cbcl)

# Clean Global Enviorment 
rm(UO_T1_cbcl, UO_T2_cbcl, UO_T3_cbcl, UO_T4_cbcl, UPMC_T1_cbcl, UPMC_T2_cbcl, UPMC_T3_cbcl, UPMC_T4_cbcl, 
   old_UO_cbcl_names_T1, old_UO_cbcl_names_T2, old_UO_cbcl_names_T3, old_UO_cbcl_names_T4, old_UPMC_cbcl_names_T1_T4, old_UPMC_cbcl_names_T2_T3)

# Create the Predigree data for each Time Point
# Resolve issue with relationship column
Pedigree_T1 <- select(Pedigree, FamID, child_guid, child_FamID = FamID_Child, child_sex = ChildGender, interview_age = ChildAge_T1, interview_date = Time1Date, GroupAssignment)
Pedigree_T2 <- select(Pedigree, FamID, child_guid, child_FamID = FamID_Child, child_sex = ChildGender, interview_age = ChildAge_T2, interview_date = Time2Date, GroupAssignment)
Pedigree_T3 <- select(Pedigree, FamID, child_guid, child_FamID = FamID_Child, child_sex = ChildGender, interview_age = ChildAge_T3, interview_date = Time3Date, GroupAssignment)
Pedigree_T4 <- select(Pedigree, FamID, child_guid, child_FamID = FamID_Child, child_sex = ChildGender, interview_age = ChildAge_T4, interview_date = Time4Date, GroupAssignment)

# Merge Pedigree data to cbcl Time Points
cbcl_T1 <- merge(Pedigree_T1, cbcl_T1, by = 'FamID')
cbcl_T2 <- merge(Pedigree_T2, cbcl_T2, by = 'FamID')
cbcl_T3 <- merge(Pedigree_T3, cbcl_T3, by = 'FamID')
cbcl_T4 <- merge(Pedigree_T4, cbcl_T4, by = 'FamID')

# Clean Global Enviorment 
rm(Pedigree, Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4)

# Create Time Point coloumn in each cbcl Sheet and populate the cell with time point
cbcl_T1$timepoint <- "Time 1"
cbcl_T2$timepoint <- "Time 2"
cbcl_T3$timepoint <- "Time 3"
cbcl_T4$timepoint <- "Time 4"

# Rename each of the cbcl Date and Age coloumns so they match
#cbcl_T1 <- cbcl_T1 %>% rename( interview_date = Time1Date, interview_age = MomAge_T1)
#cbcl_T2 <- cbcl_T2 %>% rename( interview_date = Time2Date, interview_age = MomAge_T2)
#cbcl_T3 <- cbcl_T3 %>% rename( interview_date = Time3Date, interview_age = MomAge_T3)
#cbcl_T4 <- cbcl_T4 %>% rename( interview_date = Time4Date, interview_age = MomAge_T4)

# Bind all cbcl Time Points togeather creating the cbcl_Prep sheet
cbcl_Prep <- rbind(cbcl_T1, cbcl_T2, cbcl_T3, cbcl_T4)

# Clean Global Enviorment 
rm(cbcl_T1, cbcl_T2, cbcl_T3, cbcl_T4)

```

```{r recode}
# Recode responses into numbers
cbcl_Prep <- cbcl_Prep %>% 
  mutate_at(new_cbcl_names,
            funs(recode(., "Not True (as far as you know)" = 0, 
                        "Somewhat or Sometimes True" = 1,
                        "Very True or Often True" = 2,.default = NaN)))

```

```{r calculated columns}
# Created calculated columns
cbcl_Prep <- add_column(cbcl_Prep, cbcl_er = rowSums(cbcl_Prep[, c("srm_cbcl_021", "srm_cbcl_046", "srm_cbcl_051", "srm_cbcl_079", "srm_cbcl_082", "srm_cbcl_083", "srm_cbcl_092", 
                                                                   "srm_cbcl_097", "srm_cbcl_099")]),.after = "srm_cbcl_100")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_ad = rowSums(cbcl_Prep[, c("srm_cbcl_010", "srm_cbcl_033", "srm_cbcl_037", "srm_cbcl_043", "srm_cbcl_047", "srm_cbcl_068", "srm_cbcl_087", 
                                                                   "srm_cbcl_090")]),.after = "cbcl_er")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_sc = rowSums(cbcl_Prep[, c("srm_cbcl_001", "srm_cbcl_007", "srm_cbcl_012", "srm_cbcl_019", "srm_cbcl_024", "srm_cbcl_039", "srm_cbcl_045", 
                                                                   "srm_cbcl_052", "srm_cbcl_078", "srm_cbcl_086", "srm_cbcl_093")]),.after = "cbcl_ad")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_w = rowSums(cbcl_Prep[, c("srm_cbcl_002", "srm_cbcl_004", "srm_cbcl_023", "srm_cbcl_062", "srm_cbcl_067", "srm_cbcl_070", "srm_cbcl_071", 
                                                                  "srm_cbcl_098")]),.after = "cbcl_sc")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_sp = rowSums(cbcl_Prep[, c("srm_cbcl_022", "srm_cbcl_038", "srm_cbcl_048", "srm_cbcl_064", "srm_cbcl_074",
                                                                   "srm_cbcl_084")]),.after = "cbcl_w")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_ap = rowSums(cbcl_Prep[, c("srm_cbcl_005", "srm_cbcl_006", "srm_cbcl_056", "srm_cbcl_059",
                                                                   "srm_cbcl_095")]),.after = "cbcl_sp")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_ab = rowSums(cbcl_Prep[, c("srm_cbcl_008", "srm_cbcl_015", "srm_cbcl_016", "srm_cbcl_018", "srm_cbcl_020", "srm_cbcl_027", "srm_cbcl_029", 
                                                                   "srm_cbcl_035", "srm_cbcl_040", "srm_cbcl_042", "srm_cbcl_044", "srm_cbcl_053", "srm_cbcl_058", "srm_cbcl_066", 
                                                                   "srm_cbcl_069", "srm_cbcl_081", "srm_cbcl_085", "srm_cbcl_088", "srm_cbcl_096")]),.after = "cbcl_ap")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_op = rowSums(cbcl_Prep[, c("srm_cbcl_003", "srm_cbcl_009", "srm_cbcl_011", "srm_cbcl_013", "srm_cbcl_014", "srm_cbcl_017", "srm_cbcl_025", 
                                                                   "srm_cbcl_026", "srm_cbcl_028", "srm_cbcl_030", "srm_cbcl_031", "srm_cbcl_032", "srm_cbcl_034", "srm_cbcl_036", 
                                                                   "srm_cbcl_041", "srm_cbcl_049", "srm_cbcl_050", "srm_cbcl_054", "srm_cbcl_055", "srm_cbcl_057", "srm_cbcl_060",
                                                                   "srm_cbcl_061", "srm_cbcl_063", "srm_cbcl_065", "srm_cbcl_072", "srm_cbcl_073", "srm_cbcl_075", "srm_cbcl_076",
                                                                   "srm_cbcl_077", "srm_cbcl_080", "srm_cbcl_089", "srm_cbcl_091", "srm_cbcl_094")]),.after = "cbcl_ab")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_int = rowSums(cbcl_Prep[, c("srm_cbcl_021", "srm_cbcl_046", "srm_cbcl_051", "srm_cbcl_079", "srm_cbcl_082", "srm_cbcl_083", "srm_cbcl_092", 
                                                                    "srm_cbcl_097", "srm_cbcl_099", "srm_cbcl_010", "srm_cbcl_033", "srm_cbcl_037", "srm_cbcl_043", "srm_cbcl_047", 
                                                                    "srm_cbcl_068", "srm_cbcl_087", "srm_cbcl_090", "srm_cbcl_001", "srm_cbcl_007", "srm_cbcl_012", "srm_cbcl_019",
                                                                    "srm_cbcl_024", "srm_cbcl_039", "srm_cbcl_045", "srm_cbcl_052", "srm_cbcl_078", "srm_cbcl_086", "srm_cbcl_093", 
                                                                    "srm_cbcl_002", "srm_cbcl_004", "srm_cbcl_023", "srm_cbcl_062", "srm_cbcl_067", "srm_cbcl_070", "srm_cbcl_071",
                                                                    "srm_cbcl_098")]),.after = "cbcl_op")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_ext = rowSums(cbcl_Prep[, c("srm_cbcl_005", "srm_cbcl_006", "srm_cbcl_056", "srm_cbcl_059", "srm_cbcl_095", "srm_cbcl_008", "srm_cbcl_015",
                                                                    "srm_cbcl_016", "srm_cbcl_018", "srm_cbcl_020", "srm_cbcl_027", "srm_cbcl_029", "srm_cbcl_035", "srm_cbcl_040",
                                                                    "srm_cbcl_042", "srm_cbcl_044", "srm_cbcl_053", "srm_cbcl_058", "srm_cbcl_066", "srm_cbcl_069", "srm_cbcl_081",
                                                                    "srm_cbcl_085", "srm_cbcl_088", "srm_cbcl_096")]),.after = "cbcl_int")

cbcl_Prep <- add_column(cbcl_Prep, cbcl_total = rowSums(cbcl_Prep[, c("srm_cbcl_001", "srm_cbcl_002", "srm_cbcl_003", "srm_cbcl_004", "srm_cbcl_005", "srm_cbcl_006", "srm_cbcl_007",
                                                                      "srm_cbcl_008", "srm_cbcl_009", "srm_cbcl_010", "srm_cbcl_011", "srm_cbcl_012", "srm_cbcl_013", "srm_cbcl_014",
                                                                      "srm_cbcl_015", "srm_cbcl_016", "srm_cbcl_017", "srm_cbcl_018", "srm_cbcl_019", "srm_cbcl_020", "srm_cbcl_021",
                                                                      "srm_cbcl_022", "srm_cbcl_023", "srm_cbcl_024", "srm_cbcl_025", "srm_cbcl_026", "srm_cbcl_027", "srm_cbcl_028",
                                                                      "srm_cbcl_029", "srm_cbcl_030", "srm_cbcl_031", "srm_cbcl_032", "srm_cbcl_033", "srm_cbcl_034", "srm_cbcl_035",
                                                                      "srm_cbcl_036", "srm_cbcl_037", "srm_cbcl_038", "srm_cbcl_039", "srm_cbcl_040", "srm_cbcl_041", "srm_cbcl_042",
                                                                      "srm_cbcl_043", "srm_cbcl_044", "srm_cbcl_045", "srm_cbcl_046", "srm_cbcl_047", "srm_cbcl_048", "srm_cbcl_049",
                                                                      "srm_cbcl_050", "srm_cbcl_051", "srm_cbcl_052", "srm_cbcl_053", "srm_cbcl_054", "srm_cbcl_055", "srm_cbcl_056",
                                                                      "srm_cbcl_057", "srm_cbcl_058", "srm_cbcl_059", "srm_cbcl_060", "srm_cbcl_061", "srm_cbcl_062", "srm_cbcl_063",
                                                                      "srm_cbcl_064", "srm_cbcl_065", "srm_cbcl_066", "srm_cbcl_067", "srm_cbcl_068", "srm_cbcl_069", "srm_cbcl_070",
                                                                      "srm_cbcl_071", "srm_cbcl_072", "srm_cbcl_073", "srm_cbcl_074", "srm_cbcl_075", "srm_cbcl_076", "srm_cbcl_077",
                                                                      "srm_cbcl_078", "srm_cbcl_079", "srm_cbcl_080", "srm_cbcl_081", "srm_cbcl_082", "srm_cbcl_083", "srm_cbcl_084",
                                                                      "srm_cbcl_085", "srm_cbcl_086", "srm_cbcl_087", "srm_cbcl_088", "srm_cbcl_089", "srm_cbcl_090", "srm_cbcl_091",
                                                                      "srm_cbcl_092", "srm_cbcl_093", "srm_cbcl_094", "srm_cbcl_095", "srm_cbcl_096", "srm_cbcl_097", "srm_cbcl_098",
                                                                      "srm_cbcl_099")]),.after = "cbcl_ext")

# Experiment to condense the code. cbcl total all starts with srm_cbcl_0 but I can't seem to make it work.
# cbcl_Prep <- add_column(cbcl_Prep, cbcl_total_experiment = rowSums(cbcl_Prep, starts_with("srm_cbcl_0")),.after = "cbcl_ext")

```

```{r NDA Sheet}
# NDA Sheet ----------------------------------------------------------------------------
# Create NDA prep sheet, select all the needed columns from prep sheet
NDA_cbcl_Prep <- select(cbcl_Prep, c(subjectkey = child_guid, src_subject_id = child_FamID, sex = child_sex ,interview_age, interview_date, starts_with("srm")))

# NDA structure Column Names (work in progress)
NDA_cbcl_Names <- paste(c("cbcl56a", "cbcl1", "cbcl_nt", "cbcl_eye", "cbcl8", "cbcl10", "cbcl_out", "cbcl_wait", "cbcl_chew", "cbcl11", "cbcl_help", "cbcl49", "cbcl14", "cbcl15", "cbcl_defiant", "cbcl_dem", "cbcl20", 
                         "cbcl21", "cbcl_diar", "cbcl_disob", "cbcl_dist", "cbcl_alonsleep", "cbcl_answer", "cbcl24", "cbcl25", "cbcl_fun", "cbcl26", "cbcl_home", "cbcl_frust", "cbcl27", "cbcl_eat", "cbcl29", "cbcl_feel", "cbcl36", 
                         "cbcl37", "cbcl_every", "cbcl_upset", "cbcl_troubsleep", "cbcl56b", "cbcl_hit", "cbcl_breath", "cbcl_hurt", "cbcl_unhap", "cbcl_angry", "cbcl56c", "cbcl46", "cbcl45", "cbcl47", "cbcl53", "cbcl54", "cbcl_panic",
                         "cbcl_bow", "cbcl57", "cbcl58", "cbcl60", "cbcl62", "cbcl56d", "cbcl_punish", "cbcl_shift", "cbcl56e", "cbcl_reat", "cbcl_play", "cbcl_rock", "cbcl_bed", "cbcl_toil", "cbcl68", "cbcl_aff", "cbcl71", "cbcl_selfish",
                         "cbcl_littleaf", "cbcl_inter", "cbcl_fear", "cbcl75", "cbcl76", "cbcl_smear", "cbcl79", "cbcl_stares", "cbcl56f", "cbcl_sad", "cbcl84", "cbcl86", "cbcl87", "cbcl88", "cbcl_crie", "cbcl95", "cbcl_clean", "cbcl50",
                         "cbcl_uncoop", "cbcl102", "cbcl103", "cbcl104", "cbcl_people", "cbcl56g", "cbcl_wake", "cbcl_wand", "cbcl19", "cbcl109", "cbcl_withdr", "cbcl112", "cbcl113a"))

# Combine NDA and prep sheet
# Make sure put original NDA structure at first, because the order of the new sheet will be the order of the first item in bind_rows function
setnames(NDA_cbcl_Prep, new_cbcl_names, NDA_cbcl_Names)

# Recreate first line in orignial NDA file
# Make a empty row, with same number of column in NDA_CCBL, as first line of NDA sheet
# ncol(NDA_CCNES)  is number of columns in NDA_CBCL
NDA_CBCL <- bind_rows(NDA_CBCL,NDA_cbcl_Prep)

# Recreate first line in orignial NDA file
# Make a empty row, with same number of column in NDA_CBCL, as first line of NDA sheet
# ncol(NDA_CBCL)  is number of columns in NDA_CBCL
first_line <- matrix("", nrow = 1, ncol = ncol(NDA_CBCL))
# assign the first cell in first_line as cbcl1_5 which is the first cell in orignial NDA structure
first_line[,1] <- "cbcl1_5"
# assign the second cell in first_line as "1"
first_line[,2] <- "1"

# Create a new file in folder called cbcl1_5.csv, and put first line into this file
# cbcl1_5.csv file will be saved into same folder as current r script
write.table(first_line, file = "cbcl1_5.csv", sep = ",", append = FALSE, quote = FALSE, na = "", col.names = FALSE, row.names = FALSE)

# Append data in NDA_CCNES into cbcl1_5.csv file 
write.table(NDA_CBCL, file = 'cbcl1_5.csv', sep = ",", append = TRUE, na = "", quote = FALSE, row.names = FALSE)

```

```{r table, echo=FALSE}
# Treatment Progress sheet
# Select needed column
Progress <- select(cbcl_Prep, c(FamID, GroupAssignment, timepoint, starts_with("srm")))

# Calculate row mean for each individual  
Progress$Row_Mean <- rowMeans(select(cbcl_Prep,c(starts_with("srm"))), na.rm = T)

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress$FamID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Group by GroupAssissignment and Timepoint, and calculate the Group Mean
Progress_Mean <- Progress %>%
  group_by(GroupAssignment,timepoint,site) %>%
  summarise(GroupMean = mean(Row_Mean,na.rm = T),count = n())

# Select only UO Mean
UO <- Progress_Mean[Progress_Mean$site == "UO",]
# Select only UPMC Mean 
UPMC <- Progress_Mean[Progress_Mean$site == "UPMC",]

# Calculate Both site Mean 
Both_site_Mean <- Progress_Mean %>%
  group_by(GroupAssignment, timepoint) %>%
  summarise(BothSiteMean = mean(GroupMean,na.rm = T),n = sum(count))
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 


# Change GroupMean Column names according to site
colnames(UO)[colnames(UO) == "GroupMean"] = "UO_CBCL"
colnames(UPMC)[colnames(UPMC) == "GroupMean"] = "UPMC_CBCL"



# Combine UO,UPMC and both_site data 
Mean_Table <- data.frame(UO[,c("UO_CBCL","GroupAssignment")],UPMC[,"UPMC_CBCL"],Both_site_Mean[,c("BothSiteMean","n")])

# Convert Mean_Table, make original column as row
Mean_Table <- t(Mean_Table)

# Make Mean_Table as a data.frame
Mean_Table <- data.frame(Mean_Table)

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table, names(Mean_Table), Timepoint_names)

# Table output ----------
# Add a header 
kable(Mean_Table) %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 1, "DBT Group means" = 4, "FSU means" = 4, "Controls means" = 4))
```


