---
title: "DERS"
author: "Min Zhang, Bayan"
date: "7/26/2020"
output: pdf_document
---

```{r setup}
# Empty Global Environment
rm(list = ls())
#install.packages("flextable")
library(dplyr)
library(data.table)
library(knitr)
library(kableExtra)


knitr::opts_chunk$set(echo = TRUE, include = FALSE)
#Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

fsep <- .Platform$file.sep;

# Set the working directory ---------
# for Bryan
# setwd("C:/Users/bryan/Documents/GitHub/DataUploadAutomation/Measures/DERS")
setwd("~/Documents/Min/Coding/DataUploadAutomation/Measures/DERS")

#sentific notation, round up to 3 digits
options(digits = 3)

```

```{r Import}
# Import File ------------
# Import Pedigree and NDA Structure
Pedigree <- read.csv("Reference_Pedigree.csv")
# TODO: check first line 
NDA_ders <- read.csv("ders01_template.csv")

# Import ders Files
UO_T1_ders <- read.csv(file = 'UO_T1_Qualtrics.csv', stringsAsFactors = FALSE)
UO_T2_ders <- read.csv(file = 'UO_T2_Qualtrics.csv', stringsAsFactors = FALSE)
UO_T3_ders <- read.csv(file = 'UO_T3_Qualtrics.csv', stringsAsFactors = FALSE)
UO_T4_ders <- read.csv(file = 'UO_T4_Qualtrics.csv', stringsAsFactors = FALSE)
UPMC_T1_ders <- read.csv(file = 'UPMC_T1_ders.csv', stringsAsFactors = FALSE)
UPMC_T2_ders <- read.csv(file = 'UPMC_T2_ders.csv', stringsAsFactors = FALSE)
UPMC_T3_ders <- read.csv(file = 'UPMC_T3_ders.csv', stringsAsFactors = FALSE)
UPMC_T4_ders <- read.csv(file = 'UPMC_T4_ders.csv', stringsAsFactors = FALSE)


```

```{r Rename Columns}
# Create list of new variable names 
ders <- "srm_ders"
num_items <- seq(1:36)
new_ders_names <- paste(ders, num_items, sep = '_')

# Create list of old variable names so we can replace them with the new ones 
UO_ders_Item <- "Q137"
UPMC_ders_Item <- "Q6.1"
old_UO_ders_names <- paste(UO_ders_Item, num_items, sep = "_")
old_UPMC_ders_names <- paste(UPMC_ders_Item, num_items, sep = "_")

#create list of new header 
ders <- "ders"
number_of_survey <- seq(1:36)
NDA_names <- paste(ders,number_of_survey,sep = '')

```

```{r Prep Sheet, warning = F}
# Replace UO column names 
setnames(UO_T1_ders, old_UO_ders_names, new_ders_names)
setnames(UO_T2_ders, old_UO_ders_names, new_ders_names)
setnames(UO_T3_ders, old_UO_ders_names, new_ders_names)
setnames(UO_T4_ders, old_UO_ders_names, new_ders_names)

# Replace UPMC column names
setnames(UPMC_T1_ders, old_UPMC_ders_names, new_ders_names)
setnames(UPMC_T2_ders, old_UPMC_ders_names, new_ders_names)
setnames(UPMC_T3_ders, old_UPMC_ders_names, new_ders_names)
setnames(UPMC_T4_ders, old_UPMC_ders_names, new_ders_names)

# Edit UO ders Time 1 - 4 to have only ders quesions and the FamID. 
UO_T1_ders <- select(UO_T1_ders, c(FamID = Q221, Timepoint = Q146, contains("ders")))
UO_T2_ders <- select(UO_T2_ders, c(FamID = Q116, Timepoint = Q117, contains("ders")))
UO_T3_ders <- select(UO_T3_ders, c(FamID = Q174, Timepoint = Q176, contains("ders")))
UO_T4_ders <- select(UO_T4_ders, c(FamID = Q203, Timepoint = Q206, contains("ders")))

# Edit UPMC ders Time 1 - 4 to have only ders quesions and the FamID.
UPMC_T1_ders <- data.frame(c(select(UPMC_T1_ders, c(FamID = Q1.2, contains("ders"))), Timepoint = "1"))
UPMC_T2_ders <- data.frame(c(select(UPMC_T2_ders, c(FamID = Q1.2, contains("ders"))), Timepoint = "2")) 
UPMC_T3_ders <- data.frame(c(select(UPMC_T3_ders, c(FamID = Q1.2, contains("ders"))), Timepoint = "3"))
UPMC_T4_ders <- data.frame(c(select(UPMC_T4_ders, c(FamID = Q1.2, contains("ders"))), Timepoint = "4"))

# Bind 4 time points
DERS_Qualtrics <- bind_rows(UO_T1_ders, UO_T2_ders, UO_T3_ders, UO_T4_ders, UPMC_T1_ders, UPMC_T2_ders, UPMC_T3_ders, UPMC_T4_ders)


# Select revelent pedigree information, rename as needed. (Include GroupAssignment for treatment progross calculation.)
Pedigree_T1 <- data.frame(c(select(Pedigree, FamID, mother_FamID = FamID_Mother, mom_guid, mother_sex = MomGender, interview_date = Time1Date, interview_age = MomAge_T1, GroupAssignment), Timepoint = "1"))
Pedigree_T2 <- data.frame(c(select(Pedigree, FamID, mother_FamID = FamID_Mother, mom_guid, mother_sex = MomGender, interview_date = Time2Date, interview_age = MomAge_T2, GroupAssignment), Timepoint = "2"))
Pedigree_T3 <- data.frame(c(select(Pedigree, FamID, mother_FamID = FamID_Mother, mom_guid, mother_sex = MomGender, interview_date = Time3Date, interview_age = MomAge_T3, GroupAssignment), Timepoint = "3"))
Pedigree_T4 <- data.frame(c(select(Pedigree, FamID, mother_FamID = FamID_Mother, mom_guid, mother_sex = MomGender, interview_date = Time4Date, interview_age = MomAge_T4, GroupAssignment), Timepoint = "4"))

Pedigree_Prep <- bind_rows(Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4)

# Merge Pedigree data to ders Time Points
DERS_Prep <- merge(DERS_Qualtrics, Pedigree_Prep)

# Change gemder to F instead of False
DERS_Prep$mother_sex <- "F"

# Clean Global Enviorment 
rm(UO_T1_ders, UO_T2_ders, UO_T3_ders, UO_T4_ders, UPMC_T1_ders, UPMC_T2_ders, UPMC_T3_ders, UPMC_T4_ders, Pedigree, Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4)


```

```{r Re-code and Reverse Score}
#TODO: Prefer not to answer now as NA?
DERS_Prep <- DERS_Prep %>% 
  mutate_at(new_ders_names,
            funs(recode(., "Almost Never (0-10%)" = 1, 
                        "Sometimes (11%-35%)" = 2,
                        "About half the time (36%-65%)" = 3,
                        "Most of the time (66-90%)" = 4,
                        "Almost Always (91-100%)" = 5,.default = NaN)))

# Rename the reverse scored columns 

Reverse_ders_names <- new_ders_names
revers_ders_cols <- c("srm_ders_1", "srm_ders_2", "srm_ders_6", "srm_ders_7", "srm_ders_8", "srm_ders_10", 
                      "srm_ders_17", "srm_ders_20", "srm_ders_22","srm_ders_24", "srm_ders_34")
revers_ders_cols <- paste(revers_ders_cols, "r", sep = "")
Reverse_ders_names[c(1,2,6,7,8,10,17,20,22,24,34)] <- revers_ders_cols
setnames(DERS_Prep, new_ders_names, Reverse_ders_names)
# Reverse score certain items
DERS_Prep[,revers_ders_cols] = 6 - DERS_Prep[,revers_ders_cols]

# Recode UO groupassignment 
DERS_Prep <- DERS_Prep %>% 
  mutate_at(c("GroupAssignment"),
            funs(recode(., "Assigned Group 3 (HC)" = "Healthy", 
                        'Assigned Group 2 (FSU)' = "NO DBT",
                        'Assigned Group 1 (DBT)' = "DBT")))
```


```{r Colculated Columns}
# Craeted calcualted columns
awareness <- colnames(select(DERS_Prep, c("srm_ders_2r", "srm_ders_6r", "srm_ders_8r", "srm_ders_10r", 
                                                                          "srm_ders_17r", "srm_ders_34r")))

clarity <- colnames(select(DERS_Prep, c("srm_ders_1r", "srm_ders_4", "srm_ders_5", "srm_ders_7r",
                                                                        "srm_ders_9")))

goals <- colnames(select(DERS_Prep, c("srm_ders_13", "srm_ders_18", "srm_ders_20r", "srm_ders_26",
                                                                      "srm_ders_33")))

impulse <- colnames(select(DERS_Prep, c("srm_ders_3", "srm_ders_14", "srm_ders_19", "srm_ders_24r", 
                                                                        "srm_ders_27", "srm_ders_32")))

nonacceptance <- colnames(select(DERS_Prep, c("srm_ders_11", "srm_ders_12", "srm_ders_21", "srm_ders_23",
                                                                              "srm_ders_25", "srm_ders_29")))

strategies <- colnames(select(DERS_Prep, c("srm_ders_15", "srm_ders_16", "srm_ders_22r", "srm_ders_28",
                                                                           "srm_ders_30", "srm_ders_31", "srm_ders_35", "srm_ders_36")))
total <- colnames(select(DERS_Prep, c("srm_ders_1r", "srm_ders_2r", "srm_ders_3", "srm_ders_4", "srm_ders_5", 
                                                                      "srm_ders_6r", "srm_ders_7r", "srm_ders_8r", "srm_ders_9", "srm_ders_10r",
                                                                      "srm_ders_11", "srm_ders_12", "srm_ders_13", "srm_ders_14", "srm_ders_15",
                                                                      "srm_ders_16", "srm_ders_17r", "srm_ders_18", "srm_ders_19", "srm_ders_20r", 
                                                                      "srm_ders_21", "srm_ders_22r", "srm_ders_23", "srm_ders_24r", "srm_ders_25", 
                                                                      "srm_ders_26", "srm_ders_27", "srm_ders_28", "srm_ders_29", "srm_ders_30", 
                                                                      "srm_ders_31", "srm_ders_32", "srm_ders_33", "srm_ders_34r", "srm_ders_35", 
                                                                      "srm_ders_36")))

# Calculated raw mean --------------------------------------------------------------------------------------------------
# Calculated Columns
DERS_Prep$DERS_awareness_raw <- rowMeans(DERS_Prep[,awareness], na.rm = TRUE)
DERS_Prep$DERS_clarity_raw <- rowMeans(DERS_Prep[,clarity], na.rm = TRUE)
DERS_Prep$DERS_goals_raw <- rowMeans(DERS_Prep[,goals], na.rm = TRUE)
DERS_Prep$DERS_impulse_raw <- rowMeans(DERS_Prep[,impulse], na.rm = TRUE)
DERS_Prep$DERS_nonacceptance_raw <- rowMeans(DERS_Prep[,nonacceptance], na.rm = TRUE)
DERS_Prep$DERS_strategies_raw <- rowMeans(DERS_Prep[,strategies], na.rm = TRUE)
DERS_Prep$DERS_total_raw <- rowMeans(DERS_Prep[,total], na.rm = TRUE)

# Mean with 67% rule --------------------------------------------------------------------------------------------------
# Check NA percentage
DERS_Prep$NACheck <- rowSums(is.na(select(DERS_Prep, starts_with("srm"))))/ncol(dplyr::select(DERS_Prep, starts_with("srm")))

# New mean with 67% rule
DERS_Prep$DERS_awareness_cor <- ifelse(DERS_Prep$NACheck < 0.67, DERS_Prep$DERS_awareness_raw, "NA")
DERS_Prep$DERS_clarity_cor <- ifelse(DERS_Prep$NACheck < 0.67, DERS_Prep$DERS_clarity_raw, "NA")
DERS_Prep$DERS_goals_cor <- ifelse(DERS_Prep$NACheck < 0.67, DERS_Prep$DERS_goals_raw, "NA")
DERS_Prep$DERS_impulsecor <- ifelse(DERS_Prep$NACheck < 0.67, DERS_Prep$DERS_impulse_raw, "NA")
DERS_Prep$DERS_nonacceptance_cor <- ifelse(DERS_Prep$NACheck < 0.67, DERS_Prep$DERS_nonacceptance_raw, "NA")
DERS_Prep$DERS_strategies_cor <- ifelse(DERS_Prep$NACheck < 0.67, DERS_Prep$DERS_strategies_raw,  "NA")
DERS_Prep$DERS_total_cor <- ifelse(DERS_Prep$NACheck < 0.67, DERS_Prep$DERS_total_raw, "NA")

```

```{r NDA Sheet}
# Create NDA prep sheet, select all the needed columns from prep sheet
NDA_ders_Prep <- select(DERS_Prep, c(subjectkey = mom_guid, src_subject_id = mother_FamID, sex = mother_sex ,interview_age, interview_date, starts_with("srm")))
                         
# Combine NDA and prep sheet
# Make sure put original NDA structure at first, because the order of the new sheet will be the order of the first item in bind_rows function
setnames(NDA_ders_Prep, Reverse_ders_names, NDA_names)

# Recreate first line in orignial NDA file
# Make a empty row, with same number of column in NDA_ders, as first line of NDA sheet
# ncol(NDA_ders)  is number of columns in NDA_ders
NDA_ders <- bind_rows(NDA_ders,NDA_ders_Prep)

# Recreate first line in orignial NDA file
# Make a empty row, with same number of column in NDA_ders, as first line of NDA sheet
# ncol(NDA_ders)  is number of columns in NDA_ders
first_line <- matrix("", nrow = 1, ncol = ncol(NDA_ders))
# assign the firt cell in first_line as ders which is the first cell in orignial NDA structure
first_line[,1] <- "ders"
# assign the second cell in first_lineas ders
first_line[,2] <- "1"


# NDA output ---------
# Create a new file in folder called ders.csv, and put first line into this file
# ders.csv file will be saved into same folder as current r script
write.table(first_line, file = "ders.csv", sep = ",", append = FALSE, quote = FALSE, na = "", col.names = FALSE, row.names = FALSE)

# Append data in NDA_ders into ders.cav file 
write.table(NDA_ders, file = 'ders.csv', sep = ",", append = TRUE, na = "", quote = FALSE, row.names = FALSE)
```

```{r Table Preparation,include=F}
# Select needed column
Progress <- select(DERS_Prep, c(FamID, GroupAssignment, Timepoint, starts_with("srm"), Row_sum = DERS_total_raw, NACheck))

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress$FamID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Drop people who are less than 67% 
DERS_DROP <- Progress[Progress$NACheck > 0.67, ]
Progress67 <- Progress[Progress$NACheck <= 0.67, ]
Progress100 <- Progress[Progress$NACheck == 0, ]


```

```{r Original Table,  echo=FALSE}
# Group by GroupAssissignment and Timepoint, and calculate the Group Mean
Progress_Mean <- Progress %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(GroupMean = mean(Row_sum,na.rm = T), N_Ori = n())

# Colculate Both site Mean 
Both_site_Mean <- Progress %>%
  group_by(GroupAssignment, Timepoint) %>%
  summarise(BothSite_DERS_Mean = mean(Row_sum,na.rm = T), BothSite_Original_N = n())

## Reorder dataset base on GroupAssignment
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 

# Select only UO Mean
UO <- Progress_Mean[Progress_Mean$site == "UO",]
# Select only UPMC Mean 
UPMC <- Progress_Mean[Progress_Mean$site == "UPMC",]


# Change GroupMean Column names according to site
colnames(UO)[colnames(UO) == "GroupMean"] = "UO_DERS"
colnames(UO)[colnames(UO) == "N_Ori"] = "UO_DERS_Original_N"
colnames(UPMC)[colnames(UPMC) == "GroupMean"] = "UPMC_DERS"
colnames(UPMC)[colnames(UPMC) == "N_Ori"] = "UPMC_DERS_Original_N"


# Combine UO,UPMC and both_site data 
Mean_Table <- data.frame(UO[,c("UO_DERS")],UPMC[,"UPMC_DERS"],Both_site_Mean[,c("BothSite_DERS_Mean", "BothSite_N", "GroupAssignment")])

# Remove GroupAssignment column 
# Mean_Table <- select(Mean_Table, -c(GroupAssignment))

# Convert Mean_Table, make original column as row
Mean_Table <- t(Mean_Table)

# Make Mean_Table as a data.frame
Mean_Table <- data.frame(Mean_Table)


# Reorder Mean_Table
Mean_Table <- Mean_Table[c(5,6,7,8,9,10,11,12,1,2,3,4)]

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table, names(Mean_Table), Timepoint_names)

# Table output ----------
# Add a header 

kable(Mean_Table) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  add_header_above(c(" " = 1, "Controls Group means" = 4, "FSU Group means" = 4, "DBT Group means" = 4)) %>%
  add_header_above(c("DERS Mean Table (All Data)" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")
 
```

```{r 67% Table,  echo=FALSE}
# Group by GroupAssissignment and Timepoint, and calculate the Group Mean
Progress_Mean_67 <- Progress67 %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(GroupMean = mean(Row_sum,na.rm = T), N_67 = n())

# Colculate Both site Mean 
Both_site_Mean_67 <- Progress67 %>%
  group_by(GroupAssignment, Timepoint) %>%
  summarise(BothSite_DERS_Mean67 = mean(Row_sum,na.rm = T), BothSite_DERS_67_N = n())

## Reorder dataset base on GroupAssignment
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 

# Select only UO Mean
UO67 <- Progress_Mean_67[Progress_Mean_67$site == "UO",]
# Select only UPMC Mean 
UPMC67 <- Progress_Mean_67[Progress_Mean_67$site == "UPMC",]


# Change GroupMean Column names according to site
colnames(UO67)[colnames(UO67) == "GroupMean"] = "UO_DERS67"
colnames(UO67)[colnames(UO67) == "N_67"] = "UO_DERS_67_N"
colnames(UPMC67)[colnames(UPMC67) == "GroupMean"] = "UPMC_DERS67"
colnames(UPMC67)[colnames(UPMC67) == "N_67"] = "UPMC_DERS_67_N"


# Combine UO,UPMC and both_site data 
Mean_Table67 <- data.frame(UO67[,c("UO_DERS67")],UPMC67[,"UPMC_DERS67"],Both_site_Mean_67[,c("BothSite_DERS_Mean67","BothSite_DERS_67_N", "GroupAssignment")])

# Remove GroupAssignment column 
# Mean_Table <- select(Mean_Table, -c(GroupAssignment))

# Convert Mean_Table, make original column as row
Mean_Table67 <- t(Mean_Table67)

# Make Mean_Table as a data.frame
Mean_Table67 <- data.frame(Mean_Table67)

# Reorder Mean_Table
Mean_Table67 <- Mean_Table67[c(5,6,7,8,9,10,11,12,1,2,3,4)]

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table67, names(Mean_Table67), Timepoint_names)

# Table output ----------
# Add a header 
kable(Mean_Table67) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  add_header_above(c(" " = 1, "Controls Group means" = 4, "FSU Group means" = 4, "DBT Group means" = 4)) %>%
  add_header_above(c("DERS Mean Table" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")
 
```

```{r 100% Table,  echo=FALSE}
# Group by GroupAssissignment and Timepoint, and calculate the Group Mean
Progress_Mean_100 <- Progress100 %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(GroupMean = mean(Row_sum,na.rm = T), N_100 = n())

# Colculate Both site Mean 
Both_site_Mean_100 <- Progress100 %>%
  group_by(GroupAssignment, Timepoint) %>%
  summarise(BothSite_DERS_Mean100 = mean(Row_sum,na.rm = T), BothSite_DERS_100_N = n())

## Reorder dataset base on GroupAssignment
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 

# Select only UO Mean
UO100 <- Progress_Mean_100[Progress_Mean_100$site == "UO",]
# Select only UPMC Mean 
UPMC100 <- Progress_Mean_100[Progress_Mean_100$site == "UPMC",]


# Change GroupMean Column names according to site
colnames(UO100)[colnames(UO100) == "GroupMean"] = "UO_DERS100"
colnames(UO100)[colnames(UO100) == "N_100"] = "UO_DERS_100_N"
colnames(UPMC100)[colnames(UPMC100) == "GroupMean"] = "UPMC_DERS100"
colnames(UPMC100)[colnames(UPMC100) == "N_100"] = "UPMC_DERS_100_N"


# Combine UO,UPMC and both_site data 
Mean_Table100 <- data.frame(UO100[,c("UO_DERS100")],UPMC100[,"UPMC_DERS100"],Both_site_Mean_100[,c("BothSite_DERS_Mean100","BothSite_DERS_100_N", "GroupAssignment")])

# Remove GroupAssignment column 
# Mean_Table <- select(Mean_Table, -c(GroupAssignment))

# Convert Mean_Table, make original column as row
Mean_Table100 <- t(Mean_Table100)

# Make Mean_Table as a data.frame
Mean_Table100 <- data.frame(Mean_Table100)

# Reorder Mean_Table
Mean_Table100 <- Mean_Table100[c(5,6,7,8,9,10,11,12,1,2,3,4)]

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table100, names(Mean_Table100), Timepoint_names)

# Table output ----------
# Add a header 
kable(Mean_Table100) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  add_header_above(c(" " = 1, "Controls Group means" = 4, "FSU Group means" = 4, "DBT Group means" = 4)) %>%
  add_header_above(c("DERS Mean Table" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")
 
```

```{r N table}
# Create N table, GroupAssignment and Timepoint are dupliced here, just checking it's align

N <- data.frame(UO[, c("Timepoint", "UO_DERS_Original_N", "GroupAssignment")],
                UO67[, c("Timepoint", "UO_DERS_67_N", "GroupAssignment")],
                UO100[, c("Timepoint", "UO_DERS_100_N", "GroupAssignment")],
                UPMC[, c("Timepoint", "UPMC_DERS_Original_N", "GroupAssignment")],
                UPMC67[, c("Timepoint", "UPMC_DERS_67_N", "GroupAssignment")],
                UPMC100[, c("Timepoint", "UPMC_DERS_100_N", "GroupAssignment")],
                Both_site_Mean[,c("Timepoint", "BothSite_Original_N", "GroupAssignment")],
                Both_site_Mean_67[,c("Timepoint", "BothSite_DERS_67_N", "GroupAssignment")],
                Both_site_Mean_100[,c("Timepoint", "BothSite_DERS_100_N", "GroupAssignment")]
                )
# Remove dupliced column 
N <- N[,-c(1,3,4,6,7,9,10,12,13,15,16,18,19,21,22,24,25,27)]


# Convert data frame to numeric
N <- as.data.frame(sapply(N, as.numeric))

# Transfer N table from Horzontal to Vertical
N <- data.frame(t(N))

# Colculate Total N 
N$T1 <- rowSums(N[,c(1,5,9)])
N$T2 <- rowSums(N[,c(2,6,10)])
N$T3 <- rowSums(N[,c(3,7,11)])
N$T4 <- rowSums(N[,c(4,8,12)])

# Timepoint names 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4", "T1","T2", "T3", "T4")

# Rename column name 
setnames(N, names(N), Timepoint_names)

kable(N) %>%
  kable_styling(bootstrap_options = c("striped"), fixed_thead = T) %>%
  add_header_above(c(" " = 1, "DBT Group" = 4, "Control Group" = 4, "FSU Group" = 4, "Totals" = 4)) %>%
  add_header_above(c("Participant Numbers" = 17)) %>%
  column_spec(c(1,5,9,13), border_right = T, include_thead = T) %>%
  column_spec(2:17, width_min = "2cm", width_max = "2cm") %>%
  row_spec(7:9, background = "#d3d3d3")
  

```