---
title: "CCNES"
author: "Min Zhang"
date: "5/16/2020"
---

```{r setup, include = F}
# Empty Global Environment
rm(list = ls())
#install.packages("flextable")
library(dplyr)
library(data.table)
library(knitr)
library(kableExtra)


knitr::opts_chunk$set(echo = F, warning = FALSE)
#Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

fsep <- .Platform$file.sep;

# Set the working directory ---------
# for Bryan
# setwd("C:/Users/bryan/Documents/GitHub/DataUploadAutomation/Measures/CCNES")
setwd("~/Documents/Min/Coding/DataUploadAutomation/Measures/CCNES")

#sentific notation, round up to 3 digits
options(digits = 3)

```


```{r Import, echo=FALSE}
# Import File ------------
Pedigree <- read.csv("Reference_Pedigree.csv")

UO_CCNES_T1 <- read.csv("UO_T1_Qualtrics.csv")
UO_CCNES_T2 <- read.csv("UO_T2_Qualtrics.csv")
UO_CCNES_T3 <- read.csv("UO_T3_Qualtrics.csv")
UO_CCNES_T4 <- read.csv("UO_T4_Qualtrics.csv")

UPMC_CCNES_T1 <- read.csv("UPMC_T1_CCNES.csv")
UPMC_CCNES_T2 <- read.csv("UPMC_T2_CCNES.csv")
UPMC_CCNES_T3 <- read.csv("UPMC_T3_CCNES.csv")
UPMC_CCNES_T4 <- read.csv("UPMC_T4_CCNES.csv")

UO_CCNES_T1 <- UO_CCNES_T1[-c(1,2),]
UO_CCNES_T2 <- UO_CCNES_T2[-c(1,2),]
UO_CCNES_T3 <- UO_CCNES_T3[-c(1,2),]
UO_CCNES_T4 <- UO_CCNES_T4[-c(1,2),]
UPMC_CCNES_T1 <- UPMC_CCNES_T1[-c(1,2),]
UPMC_CCNES_T2 <- UPMC_CCNES_T2[-c(1,2),]
UPMC_CCNES_T3 <- UPMC_CCNES_T3[-c(1,2),]
UPMC_CCNES_T4 <- UPMC_CCNES_T4[-c(1,2),]

#NDA Structure
NDA_CCNES <- read.csv("pabq01_template.csv", skip = 1)

```

```{r Rename Columns, echo=FALSE}
## OLD UO CCNES Column Names -------------------------------------------------------------
# for each item in UO paste number 1 to 6
# sprintf used to formate str
# I use for loop because My variable name are start from different number
odd_UO_CCNES_names <- c()
for (i in sprintf("Q%03d",140:151)) {
  name <- paste(i, 1:6, sep = "_")
  odd_UO_CCNES_names <- c(odd_UO_CCNES_names, name)
}

# OLD UPMC CCNES Column Names -------------------------------------------------------------
# OLD UPMC CCNES Column Names for T1 & T4
odd_UPMC_CCNES_names <- c()
for (i in sprintf("Q10.%d",2:13)) {
  Name <- paste(i, 1:6, sep = "_")
  odd_UPMC_CCNES_names <- c(odd_UPMC_CCNES_names, Name)
}
# OLD UPMC CCNES Column Names for T2 & T3
odd_UPMC_CCNES_names2 <- c()
for (i in sprintf("Q8.%d",2:13)) {
  Name <- paste(i, 1:6, sep = "_")
  odd_UPMC_CCNES_names2 <- c(odd_UPMC_CCNES_names2, Name)
}

# CCNES prep Column Names ------------------------------------------------------------------
new_CCNES_names <- sprintf("srm_ccnes_%02d",1:72)

# NDA structure Column Names --------------------------------------------------------------
pabq <- paste("pabq",1:12, sep = "")
NDA_Names <- c()
for (i in pabq) {
  Name <- paste(i, letters[seq(1:6)], sep = "")
  NDA_Names <- c(NDA_Names, Name)
}
```

```{r Prep Sheet, echo=FALSE}
# Replace UO column names
setnames(UO_CCNES_T1, odd_UO_CCNES_names, new_CCNES_names)
setnames(UO_CCNES_T2, odd_UO_CCNES_names, new_CCNES_names)
setnames(UO_CCNES_T3, odd_UO_CCNES_names, new_CCNES_names)
setnames(UO_CCNES_T4, odd_UO_CCNES_names, new_CCNES_names)

# Replace UPMC column names
setnames(UPMC_CCNES_T1, odd_UPMC_CCNES_names, new_CCNES_names)
setnames(UPMC_CCNES_T2, odd_UPMC_CCNES_names2, new_CCNES_names)
setnames(UPMC_CCNES_T3, odd_UPMC_CCNES_names2, new_CCNES_names)
setnames(UPMC_CCNES_T4, odd_UPMC_CCNES_names, new_CCNES_names)

# Edit UO CCNES Time 1 - 4 to have only CCNES quesions, FamID and Timepoint. Rename as needed, remove first two lines 
UO_CCNES_T1 <- select(UO_CCNES_T1, c(FamID = Q221, Timepoint = Q146, contains("ccnes")))
UO_CCNES_T2 <- select(UO_CCNES_T2, c(FamID = Q116, Timepoint = Q117, contains("ccnes")))
UO_CCNES_T3 <- select(UO_CCNES_T3, c(FamID = Q174, Timepoint = Q176, contains("ccnes")))
UO_CCNES_T4 <- select(UO_CCNES_T4, c(FamID = Q203, Timepoint = Q206, contains("ccnes")))

# Edit UPMC CCNES Time 1 - 4 to have only CCNES quesions and FamID. Rename as needed
UPMC_CCNES_T1 <- data.frame(c(select(UPMC_CCNES_T1, c(FamID = Q1.2, contains("ccnes"))), Timepoint = "1"))
UPMC_CCNES_T2 <- data.frame(c(select(UPMC_CCNES_T2, c(FamID = Q1.2, contains("ccnes"))), Timepoint = "2"))  
UPMC_CCNES_T3 <- data.frame(c(select(UPMC_CCNES_T3, c(FamID = Q1.2, contains("ccnes"))), Timepoint = "3"))  
UPMC_CCNES_T4 <- data.frame(c(select(UPMC_CCNES_T4, c(FamID = Q1.2, contains("ccnes"))), Timepoint = "4"))



# Bind 4 time points
CCNES_Qualtrics <- bind_rows(UO_CCNES_T1,UO_CCNES_T2,UO_CCNES_T3,UO_CCNES_T4, UPMC_CCNES_T1, UPMC_CCNES_T2, UPMC_CCNES_T3, UPMC_CCNES_T4)

# Select revelent pedigree information, rename as needed. (Include GroupAssignment for treatment progross calculation.)
Pedigree_T1 <- data.frame(c(select(Pedigree, FamID, mother_FamID = FamID_Mother, mom_guid, mother_sex = MomGender, interview_date = Time1Date, interview_age = MomAge_T1, GroupAssignment), Timepoint = "1"))
Pedigree_T2 <- data.frame(c(select(Pedigree, FamID, mother_FamID = FamID_Mother, mom_guid, mother_sex = MomGender, interview_date = Time2Date, interview_age = MomAge_T2, GroupAssignment), Timepoint = "2"))
Pedigree_T3 <- data.frame(c(select(Pedigree, FamID, mother_FamID = FamID_Mother, mom_guid, mother_sex = MomGender, interview_date = Time3Date, interview_age = MomAge_T3, GroupAssignment), Timepoint = "3"))
Pedigree_T4 <- data.frame(c(select(Pedigree, FamID, mother_FamID = FamID_Mother, mom_guid, mother_sex = MomGender, interview_date = Time4Date, interview_age = MomAge_T4, GroupAssignment), Timepoint = "4"))

Pedigree_Prep <- bind_rows(Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4)

CCNES_PREP <- merge(CCNES_Qualtrics, Pedigree_Prep)

# Change gemder to F instead of False
CCNES_PREP$mother_sex <- "F"

# Clean Flobal Enviorment
rm(UO_CCNES_T1, UO_CCNES_T2, UO_CCNES_T3, UO_CCNES_T4, UPMC_CCNES_T1, UPMC_CCNES_T2, UPMC_CCNES_T3, UPMC_CCNES_T4,Pedigree,Pedigree_T1,Pedigree_T2,Pedigree_T3,Pedigree_T4,CCNES_T1,CCNES_T2,CCNES_T3,CCNES_T4)
```

```{r Re-code and Reverse Score,  echo=FALSE}
# Recode the strings of text to numbers 
CCNES_PREP <- CCNES_PREP %>% 
  mutate_at(new_CCNES_names,
            funs(recode(., "1 - Very Unlikely" = 1, 
                        '1' = 1,
                        '2' = 2,
                        '3' = 3,
                        '4 - Medium Liklihood' = 4,
                        '4' = 4,
                        '5' = 5,
                        '6' = 6,
                        '7' = 7,
                        '7 - Very Likely' = 7,.default = NaN)))


# Adding r at end of variable which needed to be reversed
Reverse_CCNES_names <- new_CCNES_names
Reverse_CCNES_names[c(7,39,45,55)] <- paste(new_CCNES_names[c(7,39,45,55)],"r", sep = "")
setnames(CCNES_PREP, new_CCNES_names, Reverse_CCNES_names)

# Reversed Scored
CCNES_PREP <- CCNES_PREP %>% 
  mutate_at(c("srm_ccnes_07r", "srm_ccnes_39r", "srm_ccnes_45r", "srm_ccnes_55r"),
            funs(recode(., "1" = 7, 
                        '2' = 6,
                        '3' = 5,
                        '4' = 4,
                        '5' = 3,
                        '6' = 2,
                        '7' = 1, defaut = NaN)))

# # reverse score alternative
# Reverse_CCNES_names <- new_CCNES_names
# revers_CCNES_cols <- c("srm_ccnes_07", "srm_ccnes_39", "srm_ccnes_45", "srm_ccnes_55")
# revers_CCNES_cols <- paste(revers_CCNES_cols, "r", sep = "")
# Reverse_CCNES_names[c(7,39,45,55)] <- revers_CCNES_cols
# setnames(CCNES_PREP, new_CCNES_names, Reverse_CCNES_names)
# CCNES_PREP[,revers_CCNES_cols] = 8 - CCNES_PREP[,revers_CCNES_cols]

CCNES_PREP <- CCNES_PREP %>% 
  mutate_at(c("GroupAssignment"),
            funs(recode(., "Assigned Group 3 (HC)" = "Healthy", 
                        'Assigned Group 2 (FSU)' = "NO DBT",
                        'Assigned Group 1 (DBT)' = "DBT")))


```

```{r Colculated Columns,  echo=FALSE}
# Creating list of item need to be colculated --------------------------------------------------
# list of item which needed when colculating DR
DR <- colnames(select(CCNES_PREP, c("srm_ccnes_02", "srm_ccnes_07r", "srm_ccnes_13", 
                                              "srm_ccnes_22", "srm_ccnes_29", "srm_ccnes_33", 
                                              "srm_ccnes_39r", "srm_ccnes_45r", "srm_ccnes_50", 
                                              "srm_ccnes_55r", "srm_ccnes_62", "srm_ccnes_70")))
# list of item which needed when colculating DR
PR <- colnames(select(CCNES_PREP, c("srm_ccnes_01", "srm_ccnes_12", "srm_ccnes_18", 
                                              "srm_ccnes_19", "srm_ccnes_28", "srm_ccnes_34", 
                                              "srm_ccnes_41", "srm_ccnes_47", "srm_ccnes_53", 
                                              "srm_ccnes_56", "srm_ccnes_63", "srm_ccnes_71")))

# list of item which needed when colculating EE
EE <- colnames(select(CCNES_PREP, c("srm_ccnes_05", "srm_ccnes_11", "srm_ccnes_17", 
                                              "srm_ccnes_20", "srm_ccnes_30", "srm_ccnes_35", 
                                              "srm_ccnes_42", "srm_ccnes_43", "srm_ccnes_49", 
                                              "srm_ccnes_57", "srm_ccnes_66", "srm_ccnes_68")))
# list of item which needed when colculating EFR
EFR <- colnames(select(CCNES_PREP, c("srm_ccnes_06", "srm_ccnes_08", "srm_ccnes_16", 
                                               "srm_ccnes_23", "srm_ccnes_25", "srm_ccnes_31", 
                                               "srm_ccnes_38", "srm_ccnes_48", "srm_ccnes_54",
                                               "srm_ccnes_58", "srm_ccnes_65", "srm_ccnes_69")))
# list of item which needed when colculating PFR
PFR <- colnames(select(CCNES_PREP, c("srm_ccnes_03", "srm_ccnes_10", "srm_ccnes_15", 
                                               "srm_ccnes_24", "srm_ccnes_26", "srm_ccnes_36", 
                                               "srm_ccnes_37", "srm_ccnes_44", "srm_ccnes_52",
                                               "srm_ccnes_59", "srm_ccnes_64", "srm_ccnes_67")))
# list of item which needed when colculating MR
MR <- colnames(select(CCNES_PREP, c("srm_ccnes_04", "srm_ccnes_09", "srm_ccnes_14", 
                                              "srm_ccnes_21", "srm_ccnes_27", "srm_ccnes_32", 
                                              "srm_ccnes_40", "srm_ccnes_46", "srm_ccnes_51", 
                                              "srm_ccnes_60", "srm_ccnes_61", "srm_ccnes_72")))
# Calculated raw mean --------------------------------------------------------------------------------------------------
# Calculated Columns
CCNES_PREP$ccnes_DR_raw <- rowMeans(CCNES_PREP[,DR], na.rm = TRUE)
CCNES_PREP$ccnes_PR_raw <- rowMeans(CCNES_PREP[,PR], na.rm = TRUE)
CCNES_PREP$ccnes_EE_raw <- rowMeans(CCNES_PREP[,EE], na.rm = TRUE)
CCNES_PREP$ccnes_EFR_raw <- rowMeans(CCNES_PREP[,EFR], na.rm = TRUE)
CCNES_PREP$ccnes_PFR_raw <- rowMeans(CCNES_PREP[,PFR], na.rm = TRUE)
CCNES_PREP$ccnes_MR_raw <- rowMeans(CCNES_PREP[,MR], na.rm = TRUE)
# Mean with 67% rule --------------------------------------------------------------------------------------------------
# Check NA percentage
CCNES_PREP$NACheck <- rowSums(is.na(select(CCNES_PREP, starts_with("srm"))))/ncol(dplyr::select(CCNES_PREP, starts_with("srm")))

# New mean with 67% rule
CCNES_PREP$ccnes_DR_cor <- ifelse(CCNES_PREP$NACheck < 0.67, rowMeans(CCNES_PREP[,DR], na.rm = TRUE), "NA")
CCNES_PREP$ccnes_PR_cor <- ifelse(CCNES_PREP$NACheck < 0.67, rowMeans(CCNES_PREP[,PR], na.rm = TRUE), "NA")
CCNES_PREP$ccnes_EE_cor <- ifelse(CCNES_PREP$NACheck < 0.67, rowMeans(CCNES_PREP[,EE], na.rm = TRUE), "NA")
CCNES_PREP$ccnes_EFR_cor <- ifelse(CCNES_PREP$NACheck < 0.67, rowMeans(CCNES_PREP[,EFR], na.rm = TRUE), "NA")
CCNES_PREP$ccnes_PFR_cor <- ifelse(CCNES_PREP$NACheck < 0.67, rowMeans(CCNES_PREP[,PFR], na.rm = TRUE), "NA")
CCNES_PREP$ccnes_MR_cor <- ifelse(CCNES_PREP$NACheck < 0.67, rowMeans(CCNES_PREP[,MR], na.rm = TRUE), "NA")

# progress 
# hist(CCNES_PREP$NACheck, main = "Not NA Histogram")


# Drop people who are less than 67% 
CCNES_DROP <- CCNES_PREP[CCNES_PREP$NACheck > 0.67, ]

CCNES_PREP67 <- CCNES_PREP[CCNES_PREP$NACheck <= 0.67, ]
CCNES_PREP100 <- CCNES_PREP[CCNES_PREP$NACheck == 0, ]



# Imputation -------------------------------------------------------------------------
#set(which(is.na(CCNES_PREP), 0))
```

```{r NDA Sheet,  echo=FALSE}
# Create NDA prep sheet, select all the needed columns from prep sheet
NDA_CCNES_Prep <- select(CCNES_PREP, c(subjectkey = mom_guid, src_subject_id = mother_FamID, sex = mother_sex ,interview_age, interview_date, starts_with("srm")))
                         
# Combine NDA and prep sheet
# Make sure put original NDA structure at first, because the order of the new sheet will be the order of the first item in bind_rows function
setnames(NDA_CCNES_Prep, Reverse_CCNES_names, NDA_Names)

# Recreate first line in orignial NDA file
# Make a empty row, with same number of column in NDA_CCNES, as first line of NDA sheet
NDA_CCNES[1,] <- NA
# ncol(NDA_CCNES)  is number of columns in NDA_CCNES
NDA_CCNES <- bind_rows(NDA_CCNES,NDA_CCNES_Prep)

# Recreate first line in orignial NDA file
# Make a empty row, with same number of column in NDA_CCNES, as first line of NDA sheet
# ncol(NDA_CCNES)  is number of columns in NDA_CCNES
first_line <- matrix("", nrow = 1, ncol = ncol(NDA_CCNES))
# assign the firt cell in first_line as pabq which is the first cell in orignial NDA structure
first_line[,1] <- "pabq"
# assign the second cell in first_lineas pabq
first_line[,2] <- "1"


# NDA output ---------
# Create a new file in folder called pabq.csv, and put first line into this file
# pabq.csv file will be saved into same folder as current r script
write.table(first_line, file = "pabq.csv", sep = ",", append = FALSE, quote = FALSE, na = "", col.names = FALSE, row.names = FALSE)

# Append data in NDA_CCNES into pabq.cav file 
write.table(NDA_CCNES, file = 'pabq.csv', sep = ",", append = TRUE, na = "", quote = FALSE, row.names = FALSE)
```


```{r all data Table, include = T}
# Treatment Progress sheet
# Select needed column
Progress <- select(CCNES_PREP, c(FamID, GroupAssignment, Timepoint, starts_with("srm")))

# Calculate row mean for each individual  
Progress$Supported_Mean <- rowMeans(CCNES_PREP[,c("ccnes_EE_raw","ccnes_EFR_raw", "ccnes_PFR_raw")], na.rm = TRUE)
Progress$Unsupproted_Mean <- rowMeans(CCNES_PREP[,c("ccnes_DR_raw", "ccnes_PR_raw", "ccnes_MR_raw")], na.rm = TRUE)

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress$FamID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Group by GroupAssissignment and Timepoint, and calculate the Supported_Mean and Unsupproted_Mean
Progress_Supported_Mean <- Progress %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(SupportedMean = mean(Supported_Mean,na.rm = T), n = n())

Progress_unsupported_Mean <- Progress %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(UnsupprotedMean = mean(Unsupproted_Mean,na.rm = T), n = n())

# Joint  Supported and un-supported 
Progress_Mean <- merge(Progress_Supported_Mean, Progress_unsupported_Mean)

# Select only UO Mean
UO <- Progress_Mean[Progress_Mean$site == "UO",]
# Select only UPMC Mean 
UPMC <- Progress_Mean[Progress_Mean$site == "UPMC",]

# Colculate Both site Mean 
Progress_Supported_Mean_both <- Progress %>%
  group_by(GroupAssignment,Timepoint) %>%
  summarise("BothSite_CCNES_SupportedMean" = mean(Supported_Mean,na.rm = T), n = n())

Progress_unsupported_Mean_both <- Progress %>%
  group_by(GroupAssignment,Timepoint) %>%
  summarise("BothSite_CCNES_UnsupprotedMean" = mean(Unsupproted_Mean,na.rm = T), n = n())

Both_site_Mean <- merge(Progress_Supported_Mean_both, Progress_unsupported_Mean_both)
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 


# Change GroupMean Column names according to site
colnames(UO)[colnames(UO) == "SupportedMean"] = "UO_CCNES_SupportedMean"
colnames(UO)[colnames(UO) == "UnsupprotedMean"] = "UO_CCNES_UnsupprotedMean"
colnames(UPMC)[colnames(UPMC) == "SupportedMean"] = "UPMC_CCNES_SupportedMean"
colnames(UPMC)[colnames(UPMC) == "UnsupprotedMean"] = "UPMC_CCNES_UnsupprotedMean"


# Combine UO,UPMC and both_site data 
Mean_Table <- data.frame(UO[,c("UO_CCNES_SupportedMean","UO_CCNES_UnsupprotedMean")],UPMC[,c("UPMC_CCNES_SupportedMean","UPMC_CCNES_UnsupprotedMean")],Both_site_Mean[,c("BothSite_CCNES_SupportedMean","BothSite_CCNES_UnsupprotedMean","n","GroupAssignment")])


# Remove GroupAssignment column 
# Mean_Table <- select(Mean_Table, -c(GroupAssignment))

# Convert Mean_Table, make original column as row
Mean_Table <- t(Mean_Table)

# Make Mean_Table as a data.frame
Mean_Table <- data.frame(Mean_Table)

# Reorder Mean_Table
Mean_Table <- Mean_Table[c(5,6,7,8,9,10,11,12,1,2,3,4)]

#add support /non support 
#add_column()

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table, names(Mean_Table), Timepoint_names)


# Table output ----------
# Add a header 
kable(Mean_Table) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  add_header_above(c(" " = 1, "Controls Group means (All Data)" = 4, "FSU Group means" = 4, "DBT Group means" = 4)) %>%
  add_header_above(c("CCNES Mean Table" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")
```

```{r pass 67% Table, include = T}
# Treatment Progress sheet
# Select needed column
Progress67 <- select(CCNES_PREP67, c(FamID, GroupAssignment, Timepoint, starts_with("srm")))

# Calculate row mean for each individual  
Progress67$Supported_Mean67 <- rowMeans(CCNES_PREP[,c("ccnes_EE_cor", "ccnes_EFR_cor", "ccnes_PFR_cor")], na.rm = TRUE)
Progress67$Unsupproted_Mean67 <- rowMeans(CCNES_PREP[,c("ccnes_DR_cor", "ccnes_PR_cor", "ccnes_MR_cor")], na.rm = TRUE)

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress$FamID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress67$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Group by GroupAssissignment and Timepoint, and calculate the Supported_Mean and Unsupproted_Mean
Progress_Supported_Mean67 <- Progress67 %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(SupportedMean67 = mean(Supported_Mean67,na.rm = T), n = n())

Progress_unsupported_Mean67 <- Progress67 %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(UnsupprotedMean67 = mean(Unsupproted_Mean67,na.rm = T), n = n())

# Joint  Supported and un-supported 
Progress_Mean67 <- merge(Progress_Supported_Mean67, Progress_unsupported_Mean67)

# Select only UO Mean
UO67 <- Progress_Mean67[Progress_Mean67$site == "UO",]
# Select only UPMC Mean 
UPMC67 <- Progress_Mean67[Progress_Mean67$site == "UPMC",]

# Colculate Both site Mean 
Progress_Supported_Mean_both67 <- Progress67 %>%
  group_by(GroupAssignment,Timepoint) %>%
  summarise("BothSite_CCNES_SupportedMean67" = mean(Supported_Mean67, na.rm = T), n = n())

Progress_unsupported_Mean_both67 <- Progress67 %>%
  group_by(GroupAssignment,Timepoint) %>%
  summarise("BothSite_CCNES_UnsupprotedMean67" = mean(Unsupproted_Mean67,na.rm = T), n = n())

Both_site_Mean67 <- merge(Progress_Supported_Mean_both67, Progress_unsupported_Mean_both67)
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 


# Change GroupMean Column names according to site
colnames(UO67)[colnames(UO67) == "SupportedMean67"] = "UO_CCNES_SupportedMean"
colnames(UO67)[colnames(UO67) == "UnsupprotedMean67"] = "UO_CCNES_UnsupprotedMean"
colnames(UPMC67)[colnames(UPMC67) == "SupportedMean67"] = "UPMC_CCNES_SupportedMean"
colnames(UPMC67)[colnames(UPMC67) == "UnsupprotedMean67"] = "UPMC_CCNES_UnsupprotedMean"


# Combine UO,UPMC and both_site data 
Mean_Table67 <- data.frame(UO[,c("UO_CCNES_SupportedMean","UO_CCNES_UnsupprotedMean")],UPMC[,c("UPMC_CCNES_SupportedMean","UPMC_CCNES_UnsupprotedMean")],Both_site_Mean[,c("BothSite_CCNES_SupportedMean","BothSite_CCNES_UnsupprotedMean","n","GroupAssignment")])


# Remove GroupAssignment column 
# Mean_Table <- select(Mean_Table, -c(GroupAssignment))

# Convert Mean_Table, make original column as row
Mean_Table67 <- t(Mean_Table67)

# Make Mean_Table as a data.frame
Mean_Table67 <- data.frame(Mean_Table67)

# Reorder Mean_Table
Mean_Table67 <- Mean_Table67[c(5,6,7,8,9,10,11,12,1,2,3,4)]

#add support /non support 
#add_column()

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table67, names(Mean_Table67), Timepoint_names)


# Table output ----------
# Add a header 
kable(Mean_Table67) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  add_header_above(c(" " = 1, "Controls Group means with 67% rule" = 4, "FSU Group means" = 4, "DBT Group means" = 4)) %>%
  add_header_above(c("CCNES Mean Table" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")
```

```{r pass 100% Table, include = T}
# Treatment Progress sheet
# Select needed column
Progress100 <- select(CCNES_PREP100, c(FamID, GroupAssignment, Timepoint, starts_with("srm")))

# Calculate row mean for each individual  
Progress100$Supported_Mean100 <- rowMeans(CCNES_PREP[,c("ccnes_EE_cor", "ccnes_EFR_cor", "ccnes_PFR_cor")], na.rm = TRUE)
Progress100$Unsupproted_Mean100 <- rowMeans(CCNES_PREP[,c("ccnes_DR_cor", "ccnes_PR_cor", "ccnes_MR_cor")], na.rm = TRUE)

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress$FamID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress100$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Group by GroupAssissignment and Timepoint, and calculate the Supported_Mean and Unsupproted_Mean
Progress_Supported_Mean100 <- Progress100 %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(SupportedMean100 = mean(Supported_Mean100,na.rm = T), n = n())

Progress_unsupported_Mean100 <- Progress100 %>%
  group_by(GroupAssignment,Timepoint,site) %>%
  summarise(UnsupprotedMean100 = mean(Unsupproted_Mean100,na.rm = T), n = n())

# Joint  Supported and un-supported 
Progress_Mean100 <- merge(Progress_Supported_Mean100, Progress_unsupported_Mean100)

# Select only UO Mean
UO100 <- Progress_Mean100[Progress_Mean100$site == "UO",]
# Select only UPMC Mean 
UPMC100 <- Progress_Mean100[Progress_Mean100$site == "UPMC",]

# Colculate Both site Mean 
Progress_Supported_Mean_both100 <- Progress100 %>%
  group_by(GroupAssignment,Timepoint) %>%
  summarise("BothSite_CCNES_SupportedMean100" = mean(Supported_Mean100, na.rm = T), n = n())

Progress_unsupported_Mean_both100 <- Progress100 %>%
  group_by(GroupAssignment,Timepoint) %>%
  summarise("BothSite_CCNES_UnsupprotedMean100" = mean(Unsupproted_Mean100,na.rm = T), n = n())

Both_site_Mean100 <- merge(Progress_Supported_Mean_both100, Progress_unsupported_Mean_both100)
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 


# Change GroupMean Column names according to site
colnames(UO100)[colnames(UO100) == "SupportedMean100"] = "UO_CCNES_SupportedMean"
colnames(UO100)[colnames(UO100) == "UnsupprotedMean100"] = "UO_CCNES_UnsupprotedMean"
colnames(UPMC100)[colnames(UPMC100) == "SupportedMean100"] = "UPMC_CCNES_SupportedMean"
colnames(UPMC100)[colnames(UPMC100) == "UnsupprotedMean100"] = "UPMC_CCNES_UnsupprotedMean"


# Combine UO,UPMC and both_site data 
Mean_Table100 <- data.frame(UO[,c("UO_CCNES_SupportedMean","UO_CCNES_UnsupprotedMean")],UPMC[,c("UPMC_CCNES_SupportedMean","UPMC_CCNES_UnsupprotedMean")],Both_site_Mean[,c("BothSite_CCNES_SupportedMean","BothSite_CCNES_UnsupprotedMean","n","GroupAssignment")])


# Remove GroupAssignment column 
# Mean_Table <- select(Mean_Table, -c(GroupAssignment))

# Convert Mean_Table, make original column as row
Mean_Table100 <- t(Mean_Table100)

# Make Mean_Table as a data.frame
Mean_Table100 <- data.frame(Mean_Table100)

# Reorder Mean_Table
Mean_Table100 <- Mean_Table100[c(5,6,7,8,9,10,11,12,1,2,3,4)]

#add support /non support 
#add_column()

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table100, names(Mean_Table100), Timepoint_names)


# Table output ----------
# Add a header 
kable(Mean_Table100) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  add_header_above(c(" " = 1, "Controls Group means with 100% rule" = 4, "FSU Group means" = 4, "DBT Group means" = 4)) %>%
  add_header_above(c("CCNES Mean Table" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")
```

***Used CCNES Validation subscale only, information on Invalidation can be found in the data set

```{r number table, include = T}
# Orig
ID <- c(as.character(CCNES_PREP$FamID))
CCNES_PREP$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")
N_org <- CCNES_PREP %>%
  group_by(Timepoint, site, GroupAssignment) %>% 
  summarise(n_orig = n())


# 67%
ID <- c(as.character(CCNES_PREP67$FamID))
CCNES_PREP67$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")
N67 <- CCNES_PREP67 %>%
  group_by(Timepoint, site, GroupAssignment) %>% 
  summarise(n_67 = n())

# 100%
ID <- c(as.character(CCNES_PREP100$FamID))
CCNES_PREP100$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")
N100 <- CCNES_PREP100 %>%
  group_by(Timepoint, site, GroupAssignment) %>% 
  summarise(n_100 = n())

N <- cbind(N_org, N67, N100)
N <- N[,-c(5,6,7,9, 10, 11)]
N <- data.frame(t(N))


```



