---
title: "EmotionStrategies"
author: "Austin Fisenko"
date: "7/30/2020"
output: html_document
---

```{r setup}
# Empty Global Environment
rm(list = ls())
#install.packages("flextable")
library(dplyr)
library(data.table)
library(knitr)
library(kableExtra)

#Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
knitr::opts_chunk$set(echo = TRUE, include = FALSE)


fsep <- .Platform$file.sep;

# Set the working directory ---------
# for Bryan
# setwd("C:/Users/bryan/Documents/GitHub/DataUploadAutomation/Measures/EmotionStrategies")
setwd("D:/Austin/College (D-Drive)/DataUploadAutomation/Measures/EmotionStrategies")

#sentific notation, round up to 3 digits
options(digits = 3)
```

```{r Import}
Pedigree <- read.csv("Reference_Pedigree.csv", stringsAsFactors = FALSE)
Redcap_Data <- read.csv("Redcap_Data.csv", stringsAsFactors = FALSE)
NDA_ES <- read.csv("ers01_template.csv", skip = 1, stringsAsFactors = FALSE)

# Not sure why this was in the code I was referencing but I'll keep it here jst in case. 
#Pedigree <- read.csv("Reference_Pedigree.csv")
#Redcap_Data <- read.csv("Redcap_Data.csv")
#NDA_DCCS <- read.csv("dccs01_template.csv", skip=1)
```

```{r Rename Columns}
# Redcap column names for locating old names to be replaced with Prep names and NDA names
new_ES_names <- c("oc_es_hapstrat", "oc_es_hap_1", "oc_es_hap_2", "oc_es_hap_3", "oc_es_angstrat", "oc_es_ang_1", "oc_es_ang_2", "oc_es_ang_3", "oc_es_sadstrat", "oc_es_sad_1", "oc_es_sad_2", "oc_es_sad_3")
old_ES_names <- c("oc_es_hapstrat", "oc_es_h1", "oc_es_h2", "oc_es_h3", "oc_es_angstrat", "oc_es_a1", "oc_es_a2", "oc_es_a3", "oc_es_sadstrat", "oc_es_s1", "oc_es_s2", "oc_es_s3")
NDA_ES_names <- sprintf("es_%01d", 1:12)

# Replace Column Names
setnames(Redcap_Data, old_ES_names, new_ES_names)
```

```{r Prep Sheet}
# Assign timepoint base on redcap_event_name
Redcap_Data$timepoint = sapply(strsplit(as.character(Redcap_Data$redcap_event_name), split = '_', fixed = T), function(x) (x[2])) 

# Select needed columns and rename in Redcap_Data
Redcap_Data <- select(Redcap_Data, c(Fam_ID = fam_id,  timepoint, starts_with("oc_es_")))

Redcap_Data <- select(Redcap_Data, -c(oc_es_notes, oc_es_hgen, oc_es_agen, oc_es_sgen, oc_es_intblue, oc_es_intgreen, oc_es_intmom))
# Previous attempt to remove in a more concise way. starts_with failed to remove indicated columns. 
# Redcap_Data <- select(Redcap_Data, -c(oc_es_notes, oc_es_hgen, oc_es_agen, oc_es_sgen, starts_with("oc_es_int"))

# Select revelent pedigree information, rename as needed. (Include GroupAssignment for treatment progress calculation).
Pedigree_T1 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time1Date, interview_age = MomAge_T1, child_sex = ChildGender, GroupAssignment), timepoint = 1 )
Pedigree_T2 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time2Date, interview_age = MomAge_T2, child_sex = ChildGender, GroupAssignment), timepoint = 2 )
Pedigree_T3 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time3Date, interview_age = MomAge_T3, child_sex = ChildGender, GroupAssignment), timepoint = 3 )
Pedigree_T4 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time4Date, interview_age = MomAge_T4, child_sex = ChildGender, GroupAssignment), timepoint = 4 )

Pedigree_Prep <- rbind(Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4)


# Merge Predigree and redcap files
ES_PREP <- merge(Pedigree_Prep, Redcap_Data,by = c("timepoint","Fam_ID"), all = TRUE)

# Clean Environment
rm(Pedigree, Pedigree_Prep, Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4, Redcap_Data)
```

```{r Calculated Columns}

```

```{r NDA Sheet}
# Create NDA prep sheet, select all the needed columns from prep sheet
NDA_ES_Prep <- select(ES_PREP, c(subjectkey = child_guid, src_subject_id = child_famID, interview_date, interview_age, sex = child_sex, visit = timepoint, starts_with("oc_es_") ))

# Replace columns name 
setnames(NDA_ES_Prep, new_ES_names, NDA_ES_names)

# Recreate first line in orignial NDA file
NDA_ES <- bind_rows(NDA_ES, NDA_ES_Prep)
first_line <- matrix("", nrow = 1, ncol = ncol(NDA_ES))
first_line[,1] <- "ers"
# assign the second cell in first_line as 1
first_line[,2] <- "1"



# NDA output ---------
# Create a new file in folder called dccs.csv, and put first line into this file
# dccs.csv file will be saved into same folder as current r script
write.table(first_line, file = "ers01.csv", sep = ",", append = FALSE, quote = FALSE, na = "", col.names = FALSE, row.names = FALSE)

# Append data in NDA_DCCS into dccs.cav file 
write.table(NDA_ES, file = 'ers01.csv', sep = ",", append = TRUE, na = "", quote = FALSE, row.names = FALSE)
```

```{r Table, echo=FALSE}
# Treatment Progress sheet
# Select needed column
Progress <- select(ES_PREP, c(Fam_ID, GroupAssignment, timepoint, oc_es_hap_1, oc_es_hap_2, oc_es_hap_3, oc_es_ang_1, oc_es_ang_2, oc_es_ang_3, oc_es_sad_1, oc_es_sad_2, oc_es_sad_3))

# change necessary column to numeric
# There is a better way to do this but this will work for now
# Say columns 3, 6-15 and 37 of you dataframe need to be converted to numeric one could:
# dat[, c(3,6:15,37)] <- sapply(dat[, c(3,6:15,37)], as.numeric)
ES_PREP[,10:12] <- sapply(ES_PREP[,10:12],as.numeric)
ES_PREP[,14:16] <- sapply(ES_PREP[,14:16],as.numeric) 
ES_PREP[,18:20] <- sapply(ES_PREP[,18:20],as.numeric)

ES_PREP <- sapply(ES_PREP, as.numeric)

# Calculate row mean for each individual, FAILURE, currently stuck here
Progress$Row_Mean <- rowMeans(select(ES_PREP,c(starts_with("os_es_")), na.rm = T))

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress$Fam_ID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Group by GroupAssissignment and Timepoint, and calculate the Group Mean
Progress_Mean <- Progress %>%
  group_by(GroupAssignment,timepoint,site) %>%
  summarise(GroupMean = mean(Row_Mean,na.rm = T),count = n())

# Select only UO Mean
UO <- Progress_Mean[Progress_Mean$site == "UO",]
# Select only UPMC Mean 
UPMC <- Progress_Mean[Progress_Mean$site == "UPMC",]

# Colculate Both site Mean 
Both_site_Mean <- Progress_Mean %>%
  group_by(GroupAssignment, timepoint) %>%
  summarise(BothSiteMean = mean(GroupMean,na.rm = T),n = sum(count))
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 


# Change GroupMean Column names according to site
colnames(UO)[colnames(UO) == "GroupMean"] = "UO_CCNES"
colnames(UPMC)[colnames(UPMC) == "GroupMean"] = "UPMC_CCNES"



# Combine UO,UPMC and both_site data 
Mean_Table <- data.frame(UO[,c("UO_CCNES","GroupAssignment")],UPMC[,"UPMC_CCNES"],Both_site_Mean[,c("BothSiteMean","n")])

# Remove GroupAssignment column 
# Mean_Table <- select(Mean_Table, -c(GroupAssignment))

# Convert Mean_Table, make original column as row
Mean_Table <- t(Mean_Table)

# Make Mean_Table as a data.frame
Mean_Table <- data.frame(Mean_Table)

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table, names(Mean_Table), Timepoint_names)

# Table output ----------
# Add a header 
kable(Mean_Table) %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 1, "DBT Group means" = 4, "Controls means" = 4, "FSU means" = 4))
```

