---
title: "AutomatingtheDataUpload - DimensionalCardSort"
author: "Min Zhang"
date: "6/1/2020"
output: html_document
---

```{r setup}
# Empty Global Environment
rm(list = ls())
#install.packages("flextable")
# Load package
library(tidyverse)
library(dplyr)
library(data.table)
library(knitr)
library(kableExtra)

# Knit set up
# Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
knitr::opts_chunk$set(echo = TRUE, include = FALSE)

#scientific notation, round up to 3 digits
options(digits = 3)

```

```{r Import}
# Importe needed fils 
Pedigree <- read.csv("Reference_Pedigree.csv", stringsAsFactors = FALSE)
Redcap_Data <- read.csv("Redcap_Data.csv", stringsAsFactors = FALSE)
NDA_DCCS <- read.csv("dccs01_template.csv", skip = 1, stringsAsFactors = FALSE)
Pedigree <- read.csv("Reference_Pedigree.csv")
Redcap_Data <- read.csv("Redcap_Data.csv")
NDA_DCCS <- read.csv("dccs01_template.csv", skip = 1)

```

```{r Rename Columns}
# Redcap column name: oc_dcs_1:36
old_DCS_names <- sprintf("oc_dcs_%02d", 1:36)

# DCCS NDA Columns Name TODO:wait for Bryan to confirm
NDA_DCS_names <- sprintf("dcs%02d", 1:36)
```

```{r Prep Sheet}
# Assign timepoint base on redcap_event_name
Redcap_Data$timepoint = sapply(strsplit(as.character(Redcap_Data$redcap_event_name), split = '_', fixed = T), function(x) (x[2])) 

# Select needed columns and rename in Redcap_Data
Redcap_Data <- select(Redcap_Data, c(Fam_ID = fam_id,  timepoint, starts_with("oc_dcs_")))
Redcap_Data <- select(Redcap_Data, -c(oc_dcs_notes))

# Select revelent pedigree information, rename as needed. (Include GroupAssignment for treatment progross calculation.)
Pedigree_T1 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time1Date, interview_age = MomAge_T1, child_sex = ChildGender, GroupAssignment), timepoint = 1 )
Pedigree_T2 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time2Date, interview_age = MomAge_T2, child_sex = ChildGender, GroupAssignment), timepoint = 2 )
Pedigree_T3 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time3Date, interview_age = MomAge_T3, child_sex = ChildGender, GroupAssignment), timepoint = 3 )
Pedigree_T4 <- data.frame(select(Pedigree, Fam_ID =  FamID, child_guid, child_famID = FamID_Child, interview_date = Time4Date, interview_age = MomAge_T4, child_sex = ChildGender, GroupAssignment), timepoint = 4 )

# Merge 4 pedigree
Pedigree_Prep <- rbind(Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4)

# Merge Pedigree and redcap files
DCS_PREP <- merge(Pedigree_Prep, Redcap_Data,by = c("timepoint","Fam_ID"), all = TRUE)

# Clean Environment
rm(Pedigree, Pedigree_Prep, Pedigree_T1, Pedigree_T2, Pedigree_T3, Pedigree_T4, Redcap_Data)
```

```{r Re-code and Reverse Score}
# Re=-code UO Groupassignment 
DCS_PREP <- DCS_PREP %>% 
  mutate_at(c("GroupAssignment"),
            funs(recode(., "Assigned Group 3 (HC)" = "Healthy", 
                        'Assigned Group 2 (FSU)' = "NO DBT",
                        'Assigned Group 1 (DBT)' = "DBT")))
```

```{r Colculated Columns}
# TODO: apply 67% rule 
```

```{r NDA Sheet}
# Create NDA prep sheet, select all the needed columns from prep sheet
NDA_DCCS_Prep <- select(DCS_PREP, c(subjectkey = child_guid, src_subject_id = child_famID, interview_date, interview_age, sex = child_sex, visit = timepoint, starts_with("oc_dcs_") ))

# Replace columns name 
setnames(NDA_DCCS_Prep, old_DCS_names, NDA_DCS_names)

# Add empty line in original NDA file for merge
NDA_DCCS[1,] <- NA
# Recreate first line in original NDA file
NDA_DCCS <- bind_rows(NDA_DCCS, NDA_DCCS_Prep)
first_line <- matrix("", nrow = 1, ncol = ncol(NDA_DCCS))
first_line[,1] <- "dccs"
# assign the second cell in first_line as dccs
first_line[,2] <- "1"

# NDA output ####
# Create a new file in folder called dccs.csv, and put first line into this file
# dccs.csv file will be saved into same folder as current r script
write.table(first_line, file = "dccs01.csv", sep = ",", append = FALSE, quote = FALSE, na = "", col.names = FALSE, row.names = FALSE)

# Append data in NDA_DCCS into dccs.csv file 
write.table(NDA_DCCS, file = 'dccs01.csv', sep = ",", append = TRUE, na = "", quote = FALSE, row.names = FALSE)
```


```{r Table,  echo=FALSE}
# Treatment Progress sheet
# Select needed column
Progress <- select(DCS_PREP, c(Fam_ID, GroupAssignment, timepoint, starts_with("oc_dcs_")))

# Calculate row mean for each individual  ss
Progress$Row_Mean <- rowMeans(select(DCS_PREP,c(starts_with("oc_dcs_"))), na.rm = T)

# Change FamId as character and assign to ID variable 
ID <- c(as.character(Progress$Fam_ID))

# Add Site column to Progress, if ID start with 9 then site is UO, else is UPMC
Progress$site <- ifelse(startsWith(ID, "9"),"UO","UPMC")

# Group by GroupAssissignment and Timepoint, and calculate the Group Mean
Progress_Mean <- Progress %>%
  group_by(GroupAssignment,timepoint,site) %>%
  summarise(GroupMean = mean(Row_Mean, na.rm = T),count = n())

# Select only UO Mean
UO <- Progress_Mean[Progress_Mean$site == "UO",]
# Select only UPMC Mean 
UPMC <- Progress_Mean[Progress_Mean$site == "UPMC",]

# Colculate Both site Mean 
Both_site_Mean <- Progress %>%
  group_by(GroupAssignment, timepoint) %>%
  summarise(BothSite_DimensionalCardSort_Mean = mean(Row_Mean,na.rm = T),n = n())
#Progress_Mean <- Progress_Mean[order(GroupAssignment),] 


# Change GroupMean Column names according to site
colnames(UO)[colnames(UO) == "GroupMean"] = "UO_DimensionalCardSort"
colnames(UPMC)[colnames(UPMC) == "GroupMean"] = "UPMC_DimensionalCardSort"

# Combine UO,UPMC and both_site data 
Mean_Table <- data.frame(UO[,c("UO_DimensionalCardSort")],UPMC[,"UPMC_DimensionalCardSort"],Both_site_Mean[,c("BothSite_DimensionalCardSort_Mean","n","GroupAssignment")])

# Convert Mean_Table, make original column as row
Mean_Table <- t(Mean_Table)

# Make Mean_Table as a data.frame
Mean_Table <- data.frame(Mean_Table)

# Reorder Mean_Table
Mean_Table <- Mean_Table[c(5,6,7,8,9,10,11,12,1,2,3,4)]

# Add Timepoint column 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4")

# Rename column name 
setnames(Mean_Table, names(Mean_Table), Timepoint_names)

# Table output ####
# Add a header 
kable(Mean_Table) %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 1, "DBT Group means" = 4, "Controls Group means" = 4, "FSU Group means" = 4)) %>%
  add_header_above(c("Dimensional Card Sort Mean Table" = 13)) %>%
  column_spec(c(1,5,9), border_right = T, include_thead = T) %>%
  column_spec(c(2,3,4,5,6,7,8,9,10,11,12,13), width_min = "2cm", width_max = "2cm")
```

```{r Ns talbe}
# Original Table ####
# Original by site 
N_ori <- Progress %>%
  group_by(Timepoint, site, GroupAssignment) %>% 
  summarise(n_ori = n())

# Original both site 
N_ori_BothSite <- Progress %>%
  group_by(Timepoint, GroupAssignment) %>% 
  summarise(BothSite_Original_N = n())


#### 67% table ####
# 67% by site 
N67 <- Progress67 %>%
  group_by(Timepoint, site, GroupAssignment) %>% 
  summarise(n_67 = n())

# 67% both site 
N67_BothSite <- Progress67 %>%
  group_by(Timepoint, GroupAssignment) %>% 
  summarise(BothSite_67_N = n())

#### 100% table ####
N100 <- Progress100 %>%
  group_by(Timepoint, site, GroupAssignment) %>% 
  summarise(n_100 = n())

# 100% both site 
N100_BothSite <- Progress100 %>%
  group_by(Timepoint, GroupAssignment) %>% 
  summarise(BothSite_100_N = n())



#### N table ####

# combine all three n table 
N_bySite <- merge(N_ori, N67, all = T)
N_bySite <- merge(N_bySite,N100, all = T)
# Bind both site data 
BothSite_N <- merge(N_ori_BothSite, N67_BothSite, all = T)
BothSite_N <- merge(BothSite_N, N100_BothSite, all = T)

# Seperate UO and UPMC data 
UO_N <- data.frame(N_bySite[N_bySite$site == "UO",])
UPMC_N <- data.frame(N_bySite[N_bySite$site == "UPMC",])


# Change column names 
colnames(UO_N)[colnames(UO_N) == "n_ori"] = "UO_CCNES_Original_N"
colnames(UO_N)[colnames(UO_N) == "n_67"] = "UO_CCNES_67_N"
colnames(UO_N)[colnames(UO_N) == "n_100"] = "UO_CCNES_100_N"

colnames(UPMC_N)[colnames(UPMC_N) == "n_ori"] = "UPMC_CCNES_Original_N"
colnames(UPMC_N)[colnames(UPMC_N) == "n_67"] = "UPMC_CCNES_67_N"
colnames(UPMC_N)[colnames(UPMC_N) == "n_100"] = "UPMC_CCNES_100_N"


# Create N table (Selecting columns from UO_N, UPMC_N, BothSite_N) GroupAssignment included twice here, just checking it's align
N <- data.frame(UO_N[, c("Timepoint","UO_CCNES_Original_N", "UO_CCNES_67_N", "UO_CCNES_100_N")], 
                UPMC_N[, c("UPMC_CCNES_Original_N", "UPMC_CCNES_67_N", "UPMC_CCNES_100_N", "GroupAssignment")],
                BothSite_N[, c("BothSite_Original_N", "BothSite_67_N", "BothSite_100_N", "GroupAssignment")])

# Reorder N table base on GroupAssignment 
N <- N[order(N$GroupAssignment),]

# Convert data frame to numeric
N <- as.data.frame(sapply(N, as.numeric))

# Transfer N table from Horzontal to Vertical
N <- data.frame(t(N))

# Colculate Total N 
N$T1 <- rowSums(N[,c(1,5,9)], na.rm = T)
N$T2 <- rowSums(N[,c(2,6,10)], na.rm = T)
N$T3 <- rowSums(N[,c(3,7,11)], na.rm = T)
N$T4 <- rowSums(N[,c(4,8,12)], na.rm = T)

# Timepoint names 
Timepoint_names <- c("T1","T2", "T3", "T4","T1","T2", "T3", "T4","T1","T2", "T3", "T4", "T1","T2", "T3", "T4")

# Rename column name 
setnames(N, names(N), Timepoint_names)

# Remove un-needed column
N <- N[-c(1,8,12),]



# Remove un-needed lines in table
# N <- N[-c(1,2,3),]

# Total number calculation 


kable(N) %>%
  kable_styling(bootstrap_options = c("striped"), fixed_thead = T) %>%
  add_header_above(c(" " = 1, "DBT Group" = 4, "Control Group" = 4, "FSU Group" = 4, "Totals" = 4)) %>%
  add_header_above(c("Participant Numbers" = 17)) %>%
  column_spec(c(1,5,9,13), border_right = T, include_thead = T) %>%
  column_spec(2:17, width_min = "2cm", width_max = "2cm") %>%
  row_spec(7:9, background = "#d3d3d3")
  
```







