---
title: "SIDP"
author: "Min Zhang"
date: "11/21/2020"
output: html_document
---

# Setup
Empty environment, loading library, set knitr and scientific notation
```{r setup}
# Loading library
library(tidyverse)
library(data.table)
library(knitr)
library(kableExtra)
library(dplyr)

# Settings for knit the whole document 
# Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
knitr::opts_chunk$set(echo = F, warning = FALSE)

#scientific notation, round up to 3 digits
options(digits = 3)
```

# Import
Import measurement, Pedigree data and NDA structure
```{r Import}
# Empty Global Environment
rm(list = ls())

# Import Pedigree and NDA structure
Pedigree <- read.csv("Reference_Pedigree.csv")
NDA_SIDP <- read.csv("sidp01_template.csv", skip = 1)
SIDP_UPMC <- read.csv("SIDP_IV_UPMC 2020_01 upload.csv", skip = 1)
SIDP_UO <-  read.csv("SIDP_IV_ORE 2019_12 upload.csv")
```

#Prepation Sheet
Select relevant pedigree information, rename as needed. (Include GroupAssignment for treatment progress calculation.)
```{r Prep Sheet}
SIDP_UO$site <- "Ore" 
SIDP_UO$visit <- "Clinical intake"
SIDP <- rbind(SIDP_UO, SIDP_UPMC)

SIDP <- select(SIDP, c(FamID = src_subject_id, interview_date,  sex = gender, starts_with("par"), starts_with("scz"), starts_with("szt"), starts_with("ant"), starts_with("brd"), starts_with("hst"), starts_with("nar"), starts_with("avd"), starts_with("dpn"), starts_with("obc"), site, visit))

Pedigree <- select(Pedigree, c(child_guid, FamID, interview_age = ChildAge_Intake, GroupAssignment))

SIDP_Prep <- merge(SIDP, Pedigree, by = "FamID")
```

# Recode and Reverse-Score
```{r Re-code}
# Re-code UO Groupassignment 
SIDP_Prep <- SIDP_Prep %>% 
  mutate_at(c("GroupAssignment"),
            funs(recode(., "Assigned Group 3 (HC)" = "Healthy", 
                        'Assigned Group 2 (FSU)' = "NO DBT",
                        'Assigned Group 1 (DBT)' = "DBT")))
```

#NDA Sheet
```{r NDA Sheet}
# Create NDA Prep sheet, select all the needed columns from Prep sheet
NDA_SIDP_Prep <- SIDP_Prep %>%
  rename(src_subject_id = FamID, subjectkey = child_guid)

# Add empty line in original NDA file for merge
NDA_SIDP[1,] <- NA
# Recreate first line in original NDA file
NDA_SIDP <- bind_rows(NDA_SIDP, NDA_SIDP_Prep)
first_line <- matrix("", nrow = 1, ncol = ncol(NDA_SIDP))
first_line[,1] <- "sidp"
# assign the second cell in first_line as dccs
first_line[,2] <- "1"

# NDA output ####
# Create a new file in folder called dccs.csv, and put first line into this file
# dccs.csv file will be saved into same folder as current r script
write.table(first_line, file = "sidp01.csv", sep = ",", append = FALSE, quote = FALSE, na = "", col.names = FALSE, row.names = FALSE)

# Append data in NDA_DCCS into dccs.csv file 
write.table(NDA_SIDP, file = 'sidp01.csv', sep = ",", append = TRUE, na = "", quote = FALSE, row.names = FALSE)
```


# Ns Table
```{r Ns Table}
# N number by site 
N_bySite <- SIDP_Prep %>%
  group_by(site, GroupAssignment) %>% 
  summarise(n_bySite = n())

# N number for both site
N_Both <- SIDP_Prep %>%
  group_by(GroupAssignment) %>% 
  summarise(BothSite_N = n())

# Seperate UO and UPMC data 
UO_N <- data.frame(N_bySite[N_bySite$site == "Ore",])
UPMC_N <- data.frame(N_bySite[N_bySite$site == "Pitt",])

# rename column name
colnames(UO_N)[colnames(UO_N) == "n_bySite"] = "UO_N"
colnames(UPMC_N)[colnames(UPMC_N) == "n_bySite"] = "UPMC_N"

# Create N table (Selecting columns from UO_N, UPMC_N, BothSite_N) GroupAssignment included multiple times here, just make sure they are align, will be removed
N <- data.frame(UO_N[, c("UO_N","GroupAssignment")],
                UPMC_N[, c("UPMC_N","GroupAssignment")],
                N_Both[, c("BothSite_N", "GroupAssignment")])

# Transfer N table from Horizontal to Vertical
N <- data.frame(t(N))

# Remove un-needed column
N <- N[-c(2,4,6),]

# rename column name
N_Name <- c("DBT Group", "Control Group" , "FSU Group")
setnames(N, names(N),N_Name)

# N table output
kable(N) %>%
  kable_styling(bootstrap_options = c("striped"), fixed_thead = T) %>%
  add_header_above(c("Participant Numbers" = 4)) %>%
  row_spec(3, background = "#d3d3d3")
```







